### ISSUE TITLE
edit-config fail to remove "link-dampening-opt"

### ISSUE THREAD

**Issue by jinxud** [CESNET/libnetconf#104]
Hi,

I wanna to use below rpc message to remove "link-dampening-opt" which is under link-dampening in model. but it failed.

I think because there is no operation in the rpc message, so it will use merge. only merge the "link-dampening" this level, and still keep the link-dampening-opt, right? then libnetconf will not remove the link-dampening-opt?

    <rpc message-id="206"
      xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
          xmlns:einterface="urn:ietf:params:xml:ns:yang:my-interface"
      xmlns:eif="urn:com:my:yang:my-interfaces"
      xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"
          xmlns:elag="urn:ietf:params:xml:ns:yang:my-lag"
      xmlns:eethernet="urn:ietf:params:xml:ns:yang:my-ethernet"
      xmlns:econtext="urn:ietf:params:xml:ns:yang:my-context" 
      xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" 
      xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">
        <edit-config>
                <target>
                        <running/>
                </target>
                <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
                        <econfig:contexts>
                                <econtext:context>
                                        <econtext:context-name>test8</econtext:context-name>
                                </econtext:context>
                        </econfig:contexts>
                        <if:interfaces>                         
                                <if:interface>    
                                        <if:name>lag-lag-2</if:name>   
                                        <if:type>ianaift:ieee8023adLag</if:type>
                                        <if:enabled>true</if:enabled>
                                        <if:description>this is description for lag 1</if:description>
                                        <elag:link-group>
                                                <elag:encapsulation-dot1q/>
                                                <elag:mac-address>
                                                        <elag:mac-addr>11:22:33:44:55:66</elag:mac-addr>
                                                </elag:mac-address>
                                        </elag:link-group>                                                          
                                </if:interface> 
                                <if:interface>    
                                        <if:name>3/2</if:name>   
                                        <if:type>ianaift:ethernetCsmacd</if:type>
                                        <eethernet:ethernet> 
                                                <eethernet:link-group>lag-lag-2</eethernet:link-group>
                                                <eethernet:lacp>
                                                        <eethernet:priority>0</eethernet:priority>
                                                </eethernet:lacp>
                                                <eethernet:link-dampening/>
                                        </eethernet:ethernet>
                                </if:interface>
                        </if:interfaces>
                </config>
        </edit-config>
    </rpc>
    ]]>]]>

the old_doc in libnetconf is below:

       <?xml version="1.0"?>
       <if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces" 
       xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type" 
       xmlns:einterface="urn:ietf:params:xml:ns:yang:my-interface" 
    xmlns:elag="urn:ietf:params:xml:ns:yang:my-lag" 
    xmlns:eethernet="urn:ietf:params:xml:ns:yang:my-ethernet" 
    xmlns:wd="urn:ietf:params:xml:ns:netconf:default:1.0">
	<if:interface>
		<if:name>mgmt@local</if:name>
		<if:type>ianaift:ipForward</if:type>
		<einterface:l3-interface>
			<einterface:context>local</einterface:context>
			<einterface:ip>
				<einterface:address>
					<einterface:addr-primary>
						<einterface:addr>10.126.198.85/23</einterface:addr>
						<einterface:tag wd:default="true">0</einterface:tag>
					</einterface:addr-primary>
				</einterface:address>
			</einterface:ip>
		</einterface:l3-interface>
		<if:enabled wd:default="true">true</if:enabled>
	</if:interface>
	<if:interface>
		<if:name>lag-lag-2</if:name>
		<if:type>ianaift:ieee8023adLag</if:type>
		<if:description>this is description for lag 1</if:description>
		<elag:link-group>
			<elag:encapsulation-dot1q/>
			<elag:mac-address>
				<elag:mac-addr>11:22:33:44:55:66</elag:mac-addr>
			</elag:mac-address>
			<elag:load-balance wd:default="true">true</elag:load-balance>
		</elag:link-group>
		<if:enabled wd:default="true">true</if:enabled>
	</if:interface>
	<if:interface>
		<if:name>3/2</if:name>
		<if:type>ianaift:ethernetCsmacd</if:type>
		<if:enabled wd:default="true">true</if:enabled>
		<eethernet:ethernet>
			<eethernet:link-dampening>
				<eethernet:link-dampening-opt>
					<eethernet:up>0</eethernet:up>
					<eethernet:down>65535</eethernet:down>
					<eethernet:restart>300</eethernet:restart>
				</eethernet:link-dampening-opt>
			</eethernet:link-dampening>
			<eethernet:lacp>
				<eethernet:priority>0</eethernet:priority>
			</eethernet:lacp>
			<eethernet:link-group>lag-lag-2</eethernet:link-group>
			<eethernet:mtu wd:default="true">1500</eethernet:mtu>
		</eethernet:ethernet>
	</if:interface>
    </if:interfaces>

below is model:

    container link-dampening {
       presence "";
       description "Dampen the line state detection to reduce port flaps ";
       container link-dampening-opt {
         presence "";
         description "";
         leaf down {
           type uint16 {
             range "0..65535";
           }
           default "2500";
         }
         leaf restart {
           type uint16 {
             range "0..65535";
           }
           default "0";
         }
         leaf up {
           type uint16 {
             range "0..65535";
           }
           default "10000";
          }
       } 
     }

**Comment by michalvasko** [comment]
Hi Jin,

I am a bit confused and I don't exactly understand what the issue is. Quite naturally and according to the definition, with the merge operation you can only merge data, not delete or remove, that is why there are other operations available.

Regards,
Michal

**Comment by jinxud** [comment]
Michal,

Thanks, I understand, merge is just merge. and it is follow rfc.

Thanks
Jin
