### ISSUE TITLE
lnctool return "Data model defines no data"

### ISSUE THREAD

**Issue by macauleycheng** [CESNET/libnetconf#106]
It fail at xsltproc.
'xsltproc --output .//sal-flow-config.rng --stringparam basename ./sal-flow --stringparam target config --stringparam schema-dir /usr/local/share/libnetconf/rnglib/ /usr/local/share/libnetconf/xslt/gen-relaxng.xsl /tmp/dsdlJ96ate.dsdl'

sal-flow.yang is from https://wiki.opendaylight.org/view/OpenDaylight_OpenFlow_Plugin:YangModels

At first I think the problem is "instance identifier" type. But I find it is build-in type.
I don't know why? Do you have any idea?

**Comment by macauleycheng** [comment]
I add the --verbose switch, the result is below.

xsltIf: test ($target='data' or $target='config' or     $target='edit-config' or starts-with($target,'get'))     and not(//nma:data/rng:*)
Lookup variable 'target'
found variable 'target'
Lookup variable 'target'
found variable 'target'
xsltIf: test evaluate to 1
xsltApplySequenceConstructor: copy text Data model defines no data.
xsltCopyText: copy text Data model defines no data.
Data model defines no data.

**Comment by michalvasko** [comment]
Hi,

the new switch should help you. The problem is exactly what the message says, sal-flow.yang does not define any actual data, only groupings, rpcs and notifications. Validation files are generated for the data only (will change in libnetconf2), so xsltproc fails. Using `--no-validation` skips generating the validation files and the transAPI module source gets generated.

Regards,
Michal

**Comment by macauleycheng** [comment]
I think the new switch has some coding problem.

You add below code, but the args.no_validation only for transapi but not for validation.
if args.subcommand != 'convert' and not args.no_validation:

So, if it only use “lnctool —model xxx validation”, it may fail here.

So, I think we can change it to
“if (args.subcommand == 'validation') or (args.subcommand == 'transapi' and not args.no_validation):”

**Comment by michalvasko** [comment]
Hi,

you're right, I was too hasty, thanks.

Regards
Michal
