### ISSUE TITLE
question for clear name space in code

### ISSUE THREAD

**Issue by jinxud** [CESNET/libnetconf#107]
Hi,

just a question: I find in edit_create(), it will clear name space. Could you let me know why we need do this?

Currently, in my environment, I find a issue: the namespace prefix is longer than 20. libxml2 will strip to 20 when it cannnot find namespace and will call xmlNewReconciliedNs() to add it.

I would like to know if it is reasonable not to do clear namespace.

    static int edit_create(xmlDocPtr orig_doc, xmlNodePtr edit_node, NC_EDIT_DEFOP_TYPE defop,     xmlDocPtr model, keyList keys, const struct nacm_rpc* nacm, struct nc_err** error)
    {
	 xmlNodePtr parent = NULL, model_node;
	 int r;
	 char *msg = NULL;

	assert(orig_doc != NULL);
	assert(edit_node != NULL);
    ........
	/* remove operation attribute */
	xmlRemoveProp(xmlHasNsProp(edit_node, BAD_CAST NC_EDIT_ATTR_OP, BAD_CAST NC_NS_BASE));
	nc_clear_namespaces(edit_node);   --> clear namespace

    . ....

    }

Thanks,
Jin

**Comment by michalvasko** [comment]
Hi Jin,

it is there mainly to remove the namespace of the operation="create" attribute, it is of no use after that. While doing so, it removes any other unused namespaces, so this seems to be rather an issue of libxml2 than libnetconf. Still, clearing the namespaces is a cosmetic feature, not a functional one, so it is not necessary.

Regards,
Michal
