### ISSUE TITLE
API/ABI changes report

### ISSUE THREAD

**Issue by aponomarenko** [CESNET/libnetconf#112]
Hello,

It's great that you maintain backward binary compatibility of the library: http://libnetconf.googlecode.com/git/doc/compat_reports/.

I've recently developed a more powerful tool based on the abi-compliance-checker and abi-dumper tools: https://github.com/lvc/abi-tracker. It would be great if you can setup it instead/along your reports and make public for the Linux community.

I've created a starter package with reports for all past versions of the library generated by this tool. You can download it here: http://abi-laboratory.pro/files/libnetconf-abi-tracker.tar.gz

You can find README file in the package with detailed instructions on how to setup the tracker. The index file of the report is under the timeline/libnetconf/ subdirectory of the package.

Thank you.

![libnetconf-abi-tracker](https://cloud.githubusercontent.com/assets/1382645/9980624/e8b7be70-5fa8-11e5-9123-e1480ba756b4.jpg)

**Comment by rkrejci** [comment]
Hi Andrey, could you please share a step-by-step how to for creating what you have in the provided package? With info from the abi-monitor and abi-tracker READMEs and helps I'm not able to generate more than one report for the current version. How can I generate report for specific version (source codes)?

**Comment by aponomarenko** [comment]
Hi Radek,

Please see README file in the package. It's necessary to build several previous versions of the library by the  command `abi-monitor -build libnetconf.json`.

The `abi-monitor` tool takes sources to build from the `src/libnetconf/` directory. The packages with source codes can be downloaded by the command `abi-monitor -get libnetconf.json` if you'll point the tool to the URL with packages by the `SourceUrl` attribute or to the local directory with packages by the `SourceDir` attribute  of the `libnetconf.json` configuration file.

Currently the `abi-monitor` can only monitor tags, so in the case of libnetconf it's necessary to create packages for each branch by some script or manually and save them to the `src/libnetconf/` directory:

    0.3.1/libnetconf-0.3.1.tar.gz
    0.4.1/libnetconf-0.4.1.tar.gz
    0.5.0/libnetconf-0.5.0.tar.gz
    0.6.2/libnetconf-0.6.2.tar.gz
    0.7.1/libnetconf-0.7.1.tar.gz
    0.8.1/libnetconf-0.8.1.tar.gz
    0.9.2/libnetconf-0.9.2.tar.gz
    0.10.0/libnetconf-0.10.0.tar.gz
    ....

Once all necessary packages are built, the `abi-tracker` tool can create the ABI timeline report for all of them by the command `abi-tracker -build libnetconf.json` and recreate them by the `abi-tracker -rebuild libnetconf.json` command.

To recreate report for some specific version use command `abi-tracker -rebuild -v 0.6.2 libnetconf.json`.

Contents of the package:

`abi_dump/` — ABI dumps of previous versions of the library
`build_script/` — build script with instructions on how to build the library packages
`changelog/` — extracted changelogs from packages to view in the ABI timeline
`compat_report/` — compatibility reports for previous versions of the library
`css/` — CSS styles of the ABI timeline report
`db/` — the cache with information about created reports and built library versions
`headers_diff/` — visual diffs of installed library headers to view in the ABI timeline
`LGPL` — license file
`libnetconf.json` — configuration file, it's used by `abi-monitor` and `abi-tracker` tools
`objects_report/` — part of the ABI timeline report
`package_diff/` — pkgdiff reports to view in the ABI timeline
`public_symbols/` — list of public symbols extracted from header files, generated by the `abi-monitor`
`public_types/` — list of public types extracted from header files, generated by the `abi-monitor`
`README` — some setup instructions
`timeline/` — index file of the ABI timeline report

All of these files are generated automatically by the `abi-monitor` and `abi-tracker` tools except of `README`, `build_script`, `LGPL` and `libnetconf.json` (partially generated by `abi-monitor`).

Thank you.

**Comment by rkrejci** [comment]
Thank you Andrei, libnetconf will not change much, so it doesn't make sense to use it here. However, I have used it already in [libyang](https://github.com/CESNET/libyang/tree/devel/doc/ABI), another library I'm working on, and I will use it also in other future project - thank you again for the great tools.
