### ISSUE TITLE
x509 support

### ISSUE THREAD

**Issue by xboxyp** [CESNET/libnetconf#113]
Hi,

Do you have any plans to support ssh with x509? Using pkix-ssh may be?

Please let me know.

Thanks.

**Comment by michalvasko** [comment]
Hi,

we are currently busy working mainly on libyang then we will start libnetconf2 implementation, which may support this, but it's definitely not a priority, so I cannot tell you when it would be supported or even if. It certainly won't be supported in the current libnetconf.

Regards,
Michal

**Comment by xboxyp** [comment]
Thank you. I am curios, what is libnetconf2? What more are you planning to support in that?

**Comment by rkrejci** [comment]
Hi, in the first phase we want to support at least features currently supported in libnetconf. Main point is to optimize memory consumption, better support for YANG including integrated validation and improving/redesigning transAPI.
