### ISSUE TITLE
What is the exact use of transapi?

### ISSUE THREAD

**Issue by krishnakumar4a4** [CESNET/libnetconf#117]
Hi,
We have a netopeer server with custom yang models imported and have to perform get-config,edit-config operations on those.
I don't have any device here, I just want to make the changes reflected in the datastore using the edit-config request. Do I need to write a transpi for this operation?
I have tried to give the edit-config without any transapi and I got the errors like "Failed to apply changes on the device" and "There is no device/data that could be affected."

**Comment by rkrejci** [comment]
solved in [netopeer issue tracker](https://github.com/CESNET/netopeer/issues/59)
