### ISSUE TITLE
There is no device/data that could be affected.

### ISSUE THREAD

**Issue by krishnakumar4a4** [CESNET/libnetconf#118]
I have added turing-machine example transapi to the netopeer server.
I have imported the turing-machine.yang file on the client side(netconfC client) and changed an attribute.
```
<?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="4" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <tm:turing-machine xmlns:tm="http://example.net/turing-machine">
        <tm:transition-function>
          <tm:delta>
            <tm:label>10</tm:label>
          </tm:delta>
        </tm:transition-function>
      </tm:turing-machine>
    </config>
  </edit-config>
</rpc> 
```
I am getting the following error
```
 ##### Error Reply or Operation Failed #####
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="4">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>There is no device/data that could be affected.</error-message>
  </rpc-error>
</rpc-reply>
```
I couldn't identify the root cause of this.Could you please help?

and also could you please explain the difference between configuration callbacks,state data callbacks,rpc callbacks and file callbacks and when they are used?

**Comment by rkrejci** [comment]
The first part seems to be more Netopeer related issue than libnetconf. What is the output of the following command?
```
# netopeer-manager list
```

Ad callbacks, did you read the [transapi tutorial](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html)?

**Comment by krishnakumar4a4** [comment]
```
# netopeer-manager list
Reading the configuration from /etc/netopeer/modules.conf.d/
List of startup Netopeer modules:
ericsson-bfd@2015-08-09 (enabled)
turing-machine (enabled)
```
Yeah I have read the transapi tutorial, but still those terms are unclear to me.Please explain in brief

**Comment by rkrejci** [comment]
The problem with turing-machine is weird to me. Please, try to run the netopeer-server with verbose messages and post its output (till the `Netopeer server successfully initialized.` message):
```
# netopeer-server -v 3
```

Ad to callbacs:
* **configuration callbacs** - the most often type of callback. From the transAPI module, each such a callback is connected with some specific place in the data tree (one callback can be assigned to multiple places). When something inside the subtree of this place changes (e.g. some part of subtree is removed), libnetconf uses the callback, provides the new canfiguration and let the callback to do whatever is necessary to do to apply configuration change to the controled device/app/whatever.
* **state data callbacks** - there is actually only one such a callback per transapi module (this pitfall will be changed in libnetconf2). The callback is used when libnetconf is processing <get> operation and it needs state information from the controlled device/app/.... So it calls this callback and merge the result state data with content of the running configuration datastore.
* **rpc callbacks** - data models can define new RPCs that libnetconf is unable to handle. But it can call a callback from the transAPI module implementing the data model where the RPC is defined. This callback is supposed to do whatever is the RPC operation supposed to do.
* **file callbacks** - sometime the device or app already has its configuration file (e.g. in /etc). libnetconf provides functionality to monitor such a file and whenever it is changed, libnetconf use this callback to do whatever it is supposed to do.

**Comment by rkrejci** [comment]
Any progress in this?

**Comment by krishnakumar4a4** [comment]
Hi rkrejci,
I don't actually need transapi. We came accross this error when we thought of implementing it. Your explanation for callbacks is well understood and I sincerely thank for that. 
Later I have found that, I got this error when there is a mismatch in namespaces and request structure.

**Comment by pradyp11** [comment]
Hi rkrejci,
   I have the similar issue with the turing-machine.yang file. I'm using NETCONFc client and NETOPEER server. 

Output to # netopeer-manager list:

~/Downloads# netopeer-manager list
Reading the configuration from /usr/local/etc/netopeer/modules.conf.d/
List of startup Netopeer modules:
toaster (enabled)
ietf-system (enabled)
turing-machine (enabled)

Output to # netopeer-server -v 3:

netopeer-server[20696]: Shared memory location: /dev/shm/libnetconfshm
netopeer-server[20696]: Shared memory file libnetconfshm already exists - opening
netopeer-server[20696]: POSIX SHM File Descriptor: 4 (600B).
netopeer-server[20696]: Too many running/crashed libnetconf apps.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model nc-notifications.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model notifications.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model ietf-netconf-acm.
netopeer-server[20696]: ncds_set_validation: Relax NG validator set (//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[20696]: ncds_set_validation: Schematron validator set (//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[20696]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[20696]: Checking the default Events stream path //var/lib/libnetconf//streams/.
netopeer-server[20696]: Adding augment model "/usr/local/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
netopeer-server[20696]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[20696]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[20696]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[20696]: "ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[20696]: "inbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[20696]: "outbound-ssh" features in "ietf-netconf-server" module enabled.
netopeer-server[20696]: Datastore ietf-netconf-server initiated with ID 1804289384.
netopeer-server[20696]: Setting the default SSH configuration for the ietf-netconf-server module...
netopeer-server[20696]: callback_srv_netconf_srv_listen_srv_port: SSH listening on the port 830
netopeer-server[20696]: Adding static transapi "/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[20696]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[20696]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[20696]: "dynamic-modules" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[20696]: "ssh" features in "netopeer-cfgnetopeer" module enabled.
netopeer-server[20696]: Datastore netopeer-cfgnetopeer initiated with ID 846930887.
netopeer-server[20696]: Setting the default configuration for the cfgnetopeer module...
netopeer-server[20696]: Setting the default configuration for the cfgnetopeer module SSH...
netopeer-server[20696]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[20696]: Adding base model "/root/Downloads/sdn-mon-connectivity.yin"
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model sdn-mon-connectivity.
netopeer-server[20696]: Missing RelaxNG schema for validation (/root/Downloads/sdn-mon-connectivity-config.rng - No such file or directory).
netopeer-server[20696]: Missing Schematron stylesheet for validation (/root/Downloads/sdn-mon-connectivity-schematron.xsl - No such file or directory).
netopeer-server[20696]: Datastore sdn-mon-connectivity initiated with ID 1681692778.
netopeer-server[20696]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[20696]: Adding base model "/root/Downloads/toaster.yin"
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model toaster.
netopeer-server[20696]: Missing RelaxNG schema for validation (/root/Downloads/toaster-config.rng - No such file or directory).
netopeer-server[20696]: Missing Schematron stylesheet for validation (/root/Downloads/toaster-schematron.xsl - No such file or directory).
netopeer-server[20696]: Datastore toaster initiated with ID 1714636916.
netopeer-server[20696]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[20696]: Adding transapi "/usr/local/etc/netopeer/ietf-system/ietf-system.yin"
netopeer-server[20696]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/ietf-system/ietf-system-config.rng)
netopeer-server[20696]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/ietf-system/ietf-system-schematron.xsl)
netopeer-server[20696]: "timezone-name" features in "ietf-system" module enabled.
netopeer-server[20696]: "authentication" features in "ietf-system" module enabled.
netopeer-server[20696]: "local-users" features in "ietf-system" module enabled.
netopeer-server[20696]: Datastore ietf-system initiated with ID 1957747794.
netopeer-server[20696]: Model "ietf-system" transAPI: nothing changed.
netopeer-server[20696]: Starting FMON thread for ietf-system data model.
netopeer-server[20696]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[20696]: Adding transapi "/usr/local/etc/netopeer/turing-machine/turing-machine.yin"
netopeer-server[20696]: ncds_features_parse: no feature definitions found in data model turing-machine.
netopeer-server[20696]: Unable to monitor "/etc/ntp.conf" (No such file or directory)
netopeer-server[20696]: ncds_new_internal: Relax NG validator set (/usr/local/etc/netopeer/turing-machine/turing-machine-config.rng)
netopeer-server[20696]: ncds_new_internal: Schematron validator set (/usr/local/etc/netopeer/turing-machine/turing-machine-schematron.xsl)
netopeer-server[20696]: Datastore file /usr/local/etc/netopeer/turing-machine/datastore.xml does not exist, creating it.
netopeer-server[20696]: Datastore file /usr/local/etc/netopeer/turing-machine/datastore.xml was created.
netopeer-server[20696]: Failed to parse the datastore (/usr/local/etc/netopeer/turing-machine/datastore.xml).
netopeer-server[20696]: File /usr/local/etc/netopeer/turing-machine/datastore.xml was empty. Basic structure created.
netopeer-server[20696]: Datastore turing-machine initiated with ID 424238336.
netopeer-server[20696]: Netopeer server successfully initialized.
netopeer-server[20696]: sock_listen: could not bind "::0" port 830 (Address already in use)
netopeer-server[20696]: Server is not listening on any address!

Please help me in solving the issue. 

THnx

**Comment by michalvasko** [comment]
Hi,
your issue is not similar to the original one in this thread and it is closed anyway, you should have created a new one. Nevertheless, there are 2 problems I see.

One, the error on the 4th line says that you either have too many libnetconf applications running at the same time or you exit netopeer-server by killing it, sending it SIGKILL. Netopeer-server is properly stopped using `Ctrl + C`, which sends it SIGINT. Killing it can cause some other problems, please avoid it when you can.

Secondly, the last 2 errors say that you already have an application (could be another instance of netopeer-server) that listens on all interfaces on port 830. Quit that other application or change the interface/port that netopeer listens on in its configuration.

Regards,
Michal
