### ISSUE TITLE
Question: How to disable the NETCONF.events file ?

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/libnetconf#119]
Hi ~
I found a large file on var/lib/libnetconf/streams/NETCONF.events

How to disable the file ?  The file will very large after long time!!

After one day (24hr)
# ls -l
-rw-rw-rw-    1 root     root       2344219 Apr 21 22:37 NETCONF.events
-rw-rw-rw-    1 root     root       1048576 Apr 20 23:39 NETCONF.rules

**Comment by rkrejci** [comment]
Hi,
currently there is no way to disable it, but feel free to delete it. It stores history of events for Notifications replay.
