### ISSUE TITLE
edit_merge when handle the comment node, there is segmentfault

### ISSUE THREAD

**Issue by jinxud** [CESNET/libnetconf#120]
Hi,

we found the segment fault when libnetconf handle the edit message, and I check the code, in edit_merge function, if children->type  is neither XML_ELEMENT_NODE or XML_TEXT_NODE, the aux variable is not initialized, it will cause the error when later call other function. could you please double check?

	children = edit_node->children;
	while (children != NULL) {
		if (children->type == XML_ELEMENT_NODE) {
			if (is_key(edit_node, children, keys) != 0) {
				/* skip key elements from merging */
				children = children->next;
				continue;
			}

			aux = find_element_equiv(orig_doc, children, model, keys);
		} else if (children->type == XML_TEXT_NODE) {
			aux = find_element_equiv(orig_doc, children->parent, model, keys);
			if (aux) {
				aux = aux->children;
			}
		}

Thanks,
Jin

**Comment by rkrejci** [comment]
Thanks. Next time, please help us more with filename and line number.
