### ISSUE TITLE
SSL_read() error handling

### ISSUE THREAD

**Issue by jlm0083** [CESNET/libnetconf#122]
In `session.c`, the error handling of `SSL_read()` takes care only `c < 0`. It should be changed to `c <= 0` since the peer could shutdown TLS connection unexpectedly. Failed to handle `c == 0` causes two functions `nc_session_read_len()` and `nc_session_read_until()` fall into infinite loop.

**Comment by wirelessr** [comment]
I found the same symptom happened on `nc_session_send()`, it should handle `ret == 0` as well to avoid infinite loop.
