### ISSUE TITLE
Error: Undefined Reference to "xx" function

### ISSUE THREAD

**Issue by Yangns** [CESNET/libnetconf#123]
Hi,
I wrote a new file named "invoke.c" and added it to libnetconf module.
I thought of calling some functions present in "session.c" in "invoke.c" explicitly.
when i tried to execute "invoke.c", it is throwing an ```error undefined reference to that function``` called in "invoke.c".
I tried compilation by including all other libnetconf .c files in gcc, it threw an '``error: expected ',' or ';' before 'RCSID'.```
Help me out in solving this issue.
Thanks in advance.

```: gcc invoke.c messages.c session.c transport.c notifications.c internal.c nacm.c error.c ssh.c callbacks.c with_defaults.c
messages.c:68: error: expected ',' or ';' before 'RCSID'
session.c:90: error: expected ',' or ';' before 'RCSID'
notifications.c:71: error: expected ',' or ';' before 'RCSID'```


```: gcc invoke.c          
/tmp/cc2wz7ig.o: In function `main':
invoke.c:(.text+0x8f): undefined reference to `nc_rpc_build'
invoke.c:(.text+0xac): undefined reference to `nc_session_recv_rpc'
collect2: ld returned 1 exit status```

**Comment by michalvasko** [comment]
Hi,
I must start by saying that this is not a libnetconf issue, but a standard compilation one. Nevertheless, we did something similar in the *lncdatastore* utility, which can be found in *libnetconf/dev-tools/lncdatastore*. Look at the *Makefile.in* there and you will see that you need to define **RCSID** macro. You will need to resolve the rest of any issues you encounter yourself.

Regards,
Michal
