### ISSUE TITLE
undefined reference to `nc_invoke'

### ISSUE THREAD

**Issue by Yangns** [CESNET/libnetconf#124]
Hi,
I have called a new function``` nc_invoke``` explicitly in main() of netopeer's server.c. I'm getting an error like ```undefined reference to `nc_invoke'```. I have included invoke.h file in libnetconf.h and I have also modified the Makefile of libnetconf by including invoke.c and invoke.h files in it. Now I have configured both libnetconf and netopeer. I dont find any problem while configuring libnetconf . But when I execute ```make``` command in netopeer I'm getting the above mentioned error. 

``` 
:make
gcc -Wall -Wextra -O3 -pthread -DNP_SSH -lrt -I/usr_1/include/  -DRCSID=\""built from git 74936fb814fba710ebab"\" -I/usr/include/libxml2 .obj/src/server.o .obj/src/cfgnetopeer_transapi.o .obj/src/netconf_server_transapi.o .obj/src/ssh/server_ssh.o .obj/src/ssh/cfgnetopeer_transapi_ssh.o .obj/src/ssh/netconf_server_transapi_ssh.o -lcrypt -lssh -lnetconf -lnetconf -L/usr_1/lib/ -Wl,-rpath,/usr_1/lib  -lxml2 -o netopeer-server;
.obj/src/server.o: In function `main':
server.c:(.text+0x12c7): undefined reference to `nc_invoke'
collect2: ld returned 1 exit status
make: *** [netopeer-server] Error 1```

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
every function definition that is supposed to be callable from the shared object (library) must be preceded with "API".

Regards,
Michal
