### ISSUE TITLE
edit-config with explicit netconf:base:1.0 namespace

### ISSUE THREAD

**Issue by scottnewham** [CESNET/libnetconf#133]
I'm submitting an edit-config request to a libnetconf (0.10.0) based server. 

    <?xml version="1.0" encoding="UTF-8"?>
    <nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:8a4c94a8-9cae-11e5-ac16-0002c9350120">
    <nc:edit-config>
    <nc:target><nc:running/></nc:target>
    <config>
       ...
    </config>
    </nc:edit-config>
    </nc:rpc>

The request fails. It looks like the problem is down in ncxml_rpc_get_cfg_common where it uses the canned xpath string "/base10:rpc/base10:edit-config/base10:config"  in a call to xmlXPathEvalExpression. It doesn't seem to match anything. Will it be the case that the xpath in this instance should be "/nc:rpc/nc:edit-config/nc:config"?

If I submit an edit-config without an explicit netconf namespace it works.

Is this a known issue? If so, is there a fix or workaround?

Thanks
Scott

**Comment by michalvasko** [comment]
Hi Scott,
the *config* node is part of *input* in the *edit-config* RPC and must therefore be in the correct namespace, the same (*nc* in your example). That libnetconf not always requires it is a known issue, but in the described case it behaves as it should.

Regards,
Michal
