### ISSUE TITLE
Configure with ppc

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#135]
when I try to run the configure for a ppc host it always fails with 
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
configure: error: Missing POSIX threads support.

nothing strange can be seen in the configure.log.

**Comment by michalvasko** [comment]
Hi,
so what distribution do you use? Are you able to compile any other code that uses pthreads?

Regards,
Michal

**Comment by rkrejci** [comment]
libnetconf requires pthreads, which is not detected on your system. If you are able to compile any code that uses pthreads, it is bug in libnetconf's configure script. If not, pthreads is missing on your system, and libnetconf simply cannot be compiled.

**Comment by ntadas** [comment]
Hi,

thanks for your comments, the problem was not in the pthreads, I think the configure could be improved to give the correct error. I've checked the configure.log and saw that the actual problem was that libxslt was not found, but the error in the console is the one I mentioned above.
After installing xslt I was able to compile libnetconf.

Best Regards
Nuno

**Comment by rkrejci** [comment]
Hi, do you still have the config.log to analyze that? I'm not able to replicate the issue. Please send it to rkrejci@cesnet.cz, thanks.
