### ISSUE TITLE
Reason for moving from libssh2 to libssh

### ISSUE THREAD

**Issue by parkrish** [CESNET/libnetconf#136]
Hi,

The latest version 0.10.0 of libnetconf is using libssh ,whereas the previous version was using libssh2.
Can you please share the reason for moving from libssh2 to libssh ?
I could not make much from the release-notes.
Kindly clarify.

Thanks and regards,
Paramesh

**Comment by michalvasko** [comment]
Hi Paramesh,
the change was made mostly because libssh was required in netopeer from certain point (server-side SSH API) and we wanted to unify library requirements with libnetconf. Additionally, it solved a channel polling issue that was caused by libssh2.

Regards,
Michal
