### ISSUE TITLE
Need clarification on multi-level architecture

### ISSUE THREAD

**Issue by krishnakumar4a4** [CESNET/libnetconf#139]
Hi,

Can anyone answer the following questions

1)Does netopeer server supports multiple sessions? Do we need to provide any configuration parameters    to support that?
I also tried to add --with-dbus-services/--enable-dbus/--disable-dbus option while configuring netopeer and they are considered as unrecognizable options.

2)What exactly is a multi-level architecture and what is the role of netopeer-agent in it. Because,after configuration I couldn't see and any netopeer-agent script.

**Comment by michalvasko** [comment]
Duplicate of netopeer issue number 85.
