### ISSUE TITLE
Get datastore ID

### ISSUE THREAD

**Issue by Raaghavi** [CESNET/libnetconf#141]
Hi

I am using libnetconf-0.9.x. I wanted to do a get-config in my transapi data callback using a dummy session & use ncds_apply_rpc() to get the rpc-reply. In that case, I need the datastore ID to be passed as a parameter. Is it possible to get the datastore ID of a transapi module using libnetconf APIs?

Regards
Raaghavi Sivaguru

**Comment by rkrejci** [comment]
I'm afraid that it is not possible. Anyway the ncds_apply_rpc() is marked as deprecated in 0.9 and it was removed in 0.10, so you are supposed to use ncds_apply_rpc2all() instead and specify filter to your get-config RPC.

**Comment by michalvasko** [comment]
Hi Raaghavi,

also, if you want the config of your module, it is available to you. *node* is a pointer to the configuration of your module (either before the currently-processed change or after, depends on the operation, in 0.10.0 you can access both).

Regards,
Michal

**Comment by Raaghavi** [comment]
Hi Michal,

If I would like to do a edit-config in my code, say my rpc callback is invoking a edit-config on a different datastore. In that case, I need the datastore id of the target module to be passed as a parameter. (Even on using ncds_apply_rpc2all() API, I need a list of datastore IDs). Is there a way to access this ID? Where does libnetconf store the datastore IDs?

Regards,
Raaghavi Sivaguru

**Comment by michalvasko** [comment]
Hi Raaghavi,
datastore IDs are internal, you cannot get them if you do not remember them as return values of `ncds_init()`. I would solve your use-case by first modifying the `node` as desired (applying the edit-config yourself, hopefully it is simple enough), calling the appropriate callback yourself, and setting `config_modified` variable to actually save the new modified configuration.

Regards,
Michal

**Comment by Raaghavi** [comment]
Hi Michal,

Thanks for the explanation. I will try out your suggestion.

Regards,
Raaghavi
