### ISSUE TITLE
ncds_consolidate()

### ISSUE THREAD

**Issue by yangnpl** [CESNET/libnetconf#142]
Hi,
Can anyone explain the main purpose of ```ncds_consolidate()```?

ncds_consolidate() - consolidate all internal structures of created data stores and all data models. This function especially solves all YANG's `uses` and `augment` statements.

This also happens in ```ncds_sysinit()```,what is the specific use of ```ncds_consolidate()```?

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
this function's purpose is simple, to transform stock models into ones that can be used in libnetconf. That means resolving and applying all the syntactic statements (ones that a model could be written without, such as groupings, augments, ...).

Regards,
Michal
