### ISSUE TITLE
Rotating stream file

### ISSUE THREAD

**Issue by rponczkowski** [CESNET/libnetconf#147]
Hello,
do you have in mind any solution for rotating stream file?  As far as I know there is no clearing mechanism for this file now,  so it can grow infinitely until it took whole place on hdd.
It becomes a serious problem for embedded solutions.
Regards.
Roman Ponczkowski

**Comment by rkrejci** [comment]
Hi Roman,
we know about this, but it wasn't a big issue for as, so there are no plans to handle this automatically. It was just supposed that someone (admin) removes the files from time to time.

Do you have some ideas or proposition how it should work?

**Comment by rponczkowski** [comment]
Problem with removing file by someone is that netconf server and agents have to be restarted after that, because in current implementation notifications would stop work correctly.
General idea is to rename stream file when exceeds desired size, and mark it somehow at the end, so agent which read this file would know that need to switch to another file, when new file again exceed size remove first one, rename  current, and create new and so on.
Additionally it could be added time stamp to file names so agents could just from name know from what  time events in file starts and wouldn't need to read whole first file in case when client ask for notifications from time after new file was created.
I hope you understand what I mean.

**Comment by rponczkowski** [comment]
my implementation of the above idea:
#156

**Comment by michalvasko** [comment]
Hi,
I merged your changes and except code formatting they seemed fine, thanks.

Regards,
Michal
