### ISSUE TITLE
netopeer-agent getting stucked at pthread_rwlock_wrlock

### ISSUE THREAD

**Issue by andre-brizido** [CESNET/libnetconf#150]
Hi

Sometimes the netopeer-agent gets stuck at:
#0  pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  nc_session_monitor (session=0x2492790) at src/session.c
#2  nc_session_accept_inout (capabilities=0x24918d0, username=0x24922e0 "agorang", input=0, output=1) at src/transport.c
#3  nc_session_accept (capabilities=0x24918d0) at src/transport.c
#4  main (argc=5, argv=0x7fff1fc49648) at src/agent.c

I don't know exactly in what circunstances does it happen, but I have multiple clients connecting to the NETCONF server opening and closing sessions very often.
I'm running libnetconf from the 0.9 branch. I think the problem is related to the mmapping of the "session_list" variable. Is it safe to mmap the pthread_rwlock_t ? 
If I understood the code correctly, the intention is to share the "session_list" between multiple processes, using the pthread_rwlock_wrlock to avoid concurrency.
But according to the manual of mmap (http://man7.org/linux/man-pages/man2/mmap.2.html) changes may not be visible between processes until msync is called. I think this may be the cause of the problem.

**Comment by michalvasko** [comment]
Hi,
what you are describing is possible, but *netopeer-agent* was removed a long time ago and we ended supporting it. You can apply the fix you suggested, but my advice is to use the latest *libnetconf* and *Netopeer* from their master branches. If you encounter any problems with them, we will happily assist you.

Regards,
Michal
