### ISSUE TITLE
Load .so in libnetconf

### ISSUE THREAD

**Issue by versatildefuy** [CESNET/libnetconf#151]
Hi,
I followed the steps [here](http://libnetconf.googlecode.com/git/doc/doxygen/html/d9/d25/transapi.html) to create and compile a transapi module. Now I have the file .so in the path /usr/local/lib. My answer is: How I can load the .so into libnetconf?
Thanks.
Sorry for my english

**Comment by michalvasko** [comment]
Hi,
in very short, by calling [ncds_new_transapi()](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d8/d55/group__transapi.html#ga80e69b4cada8c35e5e358287e8af3d85). However, I would suggest for you to use [netopeer](github.com/CESNET/netopeer) (if you don't have a NETCONF server of your own). Once you install it, just use `# netopeer-manager add` with the correct parameters (path to the transAPI module is one of them). Then, once you start *netopeer-server* and connect to it, you can modify the configuration of the model your transAPI implements and the callbacks will be called as expected.

Regards,
Michal

**Comment by versatildefuy** [comment]
Thanks you so much Michal.
