### ISSUE TITLE
issue creating a custom data store

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#154]
When trying to create a custom data store I'm not able to link with libnetconf I always get this error:

undefined reference to `ncds_custom_set_data(ncds_ds*, void*, ncds_custom_funcs const*)'

I'm using several functions from libnetconf but I only get problems when I try to use this one.
I've already checked the libnetconf.so with objdump and the symbol is there.
Any ideas of what I might be missing? I've tried to remove the -lnetconf flag and I get missing references to all the other methods I'm using, so the linkage line seems to be fine and it seems to be only a problem with this function.

thanks

**Comment by michalvasko** [comment]
Hi,
this is, indeed, quite strange. However, did you copy the error exactly? Because the prototype should be `ncds_custom_set_data(ncds_ds*, void*, ncds_custom_funcs const*)`, you did not define a function with the same name and a different prototype, did you?

Regards,
Michal

**Comment by ntadas** [comment]
Hi 

the exact error is:

`lib/libnetc.so: undefined reference to 'ncds_custom_set_data(ncds_ds*, void*, ncds_custom_funcs const*)'
collect2: error: ld returned 1 exit status`

the code is:

`struct ncds_custom_funcs ncds_funcs = 
{
    .init = NetConfWrapper::init_clb,
    .free = NetConfWrapper::free_clb,
    .was_changed = NetConfWrapper::was_changed_clb,
    .rollback = NetConfWrapper::rollback_clb,
    .lock = NetConfWrapper::lock_clb,
    .unlock = NetConfWrapper::unlock_clb,
    .is_locked = NetConfWrapper::is_locked_clb,
    .getconfig = NetConfWrapper::getconfig_clb,
    .copyconfig = NetConfWrapper::copyconfig_clb,
    .deleteconfig = NetConfWrapper::deleteconfig_clb,
    .editconfig = NetConfWrapper::editconfig_clb,
};

const struct ncds_custom_funcs *ds_funcs = &(ncds_funcs); 

struct ncds_ds* ds = ncds_new(NCDS_TYPE_CUSTOM, "./build_x86/Model/ne", NULL);
ncds_custom_set_data(ds, NULL, ds_funcs);` 

I have a wrapper for the libnetconf called libnetc and I'm trying to build an executable linking against libnetc and libnetconf.
I don't think its a signature problem because I don't get any compilation error only linkage.

I see that this function is with the API prefix and I also notice that libnetconf is being compiled with -fvisibility=hidden, can this be an issue?
no other ideas.

Thanks
Regards
Nuno

**Comment by ntadas** [comment]
problem solved with this small change in my code (add the extern "C" in the include:

#ifdef __cplusplus
extern "C" {
#include <libnetconf.h>
}
#endif

don't understand why it only gives problems with this method and not all.

Cheers
Nuno

**Comment by rkrejci** [comment]
Because the header file with the `ncds_custom_set_data()` prototype misses the c++ wrapper for C headers. Other libnetconf headers have this wrapping statement. I'm going to fix it.

**Comment by ntadas** [comment]
thanks
