### ISSUE TITLE
Datastore fails to validate.

### ISSUE THREAD

**Issue by versatildefuy** [CESNET/libnetconf#155]
Hi,
I created my own module with just one leaf. I added it with netopeer-manager and then I restarted netopeer-servive. Then when I run the <validate> operation the server in mode verbose respond with this:
`netopeer-server[11281]: Received message (session 1): <?xml version="1.0" encoding="UTF-8"?>`
`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">`
` <validate>`
  `  <source>`
`      <running/>`
 `   </source>`
  `</validate>`
`</rpc>`
`netopeer-server[11281]: RelaxNG validation on subdatastore 2011254037`
`netopeer-server[11281]: subdatastore 2011254037 fails to validate`
`netopeer-server[11281]: Writing message (session 1): <?xml version="1.0" encoding="UTF-8"?>`
`<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">`
 ` <rpc-error>`
  `  <error-type>application</error-type>`
   ` <error-tag>operation-failed</error-tag>`
    `<error-severity>error</error-severity>`
  `  <error-message>Datastore fails to validate (Did not expect element example there
)</error-message>`
`  </rpc-error>`
`</rpc-reply>`

I guess the problem is I can't validate the datastore with yin scheme but I don't know how to do it. 
The module is enabled with netopeer-manager and the .yin file is in the directory transapi/module and also in the directory /usr/local/etc/netopeer/module .
how can I validate the scheme to run the edit-config operation?
Sorry for my english.
Thanks.

**Comment by michalvasko** [comment]
Hi,
most likely your data is not valid. If you cannot see why, please post the YIN model and the data you're validating (the running config), we cannot help you without them.

Regards,
Michal

**Comment by versatildefuy** [comment]
First of all thanks Michal.
Yin model: 
`<?xml version="1.0" encoding="UTF-8"?>`
`<module xmlns="urn:ietf:params:xml:ns:yang:yin:1" xmlns:ex="http://example.net/example" name="example">`
`  <namespace uri="http://example.net/example"/>`
`  <prefix value="ex"/>`
`  <description>`
`    <text>Example of data model</text>`
`  </description>`
`  <revision date="2015-12-09">`
`    <description>`
`      <text>Initial revision.</text>`
`    </description>`
`  </revision>`
`  <leaf name="ejemplo">`
`    <type name="string"/>`
`    <default value="ejemplo"/>`
`    <description>`
`      <text>descripcion</text>`
`    </description>`
`  </leaf>`
`</module>`
Running-config:
`<example xmlns="http://example.net/example">`
   `<ejemplo>string</ejemplo>`
  `</example>`

I post just the module running-config because I can validate the configuration without this module. So I guess the problem is here.

**Comment by michalvasko** [comment]
Hi,
module itself does not define any data. So, if you want to fix the model, add `<container name="example">` before the leaf and then close it after the leaf. To fix the configuration (to match the model), change the config to simply `<ejemplo xmlns="http://example.net/example">string</ejemplo>`.

Regards,
Michal

**Comment by versatildefuy** [comment]
Now works. 
Thanks Michal.
