### ISSUE TITLE
compiling libnetconf out-of-source tree

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#158]
Hi

I'm able to run the configure, compile and install libnetconf if I run the configure in the root of the libnetconf (where the configure is located ./configure).
If I create a folder build (e.g same level as the configure) and run the configure from this build folder (abs path to the configure), the makefiles are created but then I cannot compile lib netconf:  libnetconf/src/netconf_internal.h:61:20: fatal error: config.h: No such file or directory
it seems that the include paths are wrong.

this is very useful if we are compiling for different arch and we don't want to always run the configure or clean the build. Also if we use CMake to compile this lib as an external project (not in source build) this should work.

is it possible to enable libnetconf to be build out of source tree?

thanks
Best Regards

**Comment by michalvasko** [comment]
Hi,
you are correct, this is not possible. We are quite busy working on other projects aiming to replace this library (libyang, libnetconf2 - they can be built out-of-source), so if you really need it, we will gladly accept a patch, but will not spend time on it ourselves. Thank you for understanding.

Regards,
Michal

**Comment by ntadas** [comment]
ok, not a problem.
I have other options but if in the end I do some changes in libnetconf to support this I'll send you the patch.

thanks
Regards
