### ISSUE TITLE
get-schema did not return the correct content: no "error-message"

### ISSUE THREAD

**Issue by jinxud** [CESNET/libnetconf#159]
Hi,

when I use below rpc message to get the schema, the response is not fully correct, "error-message" word is missing:

    <?xml version="1.0" encoding="UTF-8"?>
     <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="85a1e34f-31e1-11e5-b826-028037ec0200">
      <ncm:get-schema xmlns:ncm="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
        <ncm:identifier>my-test</ncm:identifier>
        <ncm:version>2015-12-07</ncm:version>
        <ncm:format>yang</ncm:format>
      </ncm:get-schema>
       </rpc>
       ]]>]]>

the yang model is 

    module my-test {
      yang-version "1"; 
      namespace "urn:rdns:mytest"; 
      prefix "ifmytest";
 
      organization
        "Mytest";
 
      contact
        "Web:   <http://www.aaa.com>";
 
      description
        "my test";
 
      revision "2015-12-07" {
        description
         "initial revision";
       reference
         "rfc6020";
     }
 
     augment "/if:interfaces/if:interface/lagxipos:link-group" {
       description
         "pbr-interface";

       container forward-policy {
        presence "";
        description
        "Configure forward policy or output Configure forward
         policy";
      leaf fwd-name {
        type leafref {
          path "/ctxsipos:contexts/pbripos:forward/pbripos:fwd-"
          + "polname";
        }
        must "(../../bind-interface)" {
          error-message "zzxerr:bind this circuit to an "   =====> the "error-message" word is missing in response message
          + "interface first before configuring this type of "
          + "binding.";
          description
            "zzxdes:bind this circuit to an interface first
             before configuring this type of binding.";
        }
        mandatory true;
        description
          "Forward policy name";
      }
      leaf in {
        type empty;
        mandatory true;
        description
          "Configure inbound forward policy";
      }
      choice forward-policy-opt {
        description
          "IPOS choice";
        case ip {
          container ip {
            description
              "";
            leaf ip {
              type empty;
              mandatory true;
              description
                "Configure IP attributes";
            }
            leaf ipv6 {
              type empty;
              description
                "Configure IPV6 attributes";
            }
            leaf acl-counters {
              type empty;
              mandatory true;
              description
                "Enable ACL counters";
            }
          }
        }
        case ipv6-acl-counters {
          leaf ipv6-acl-counters {
            type empty;
            description
              "Configure IPV6 attributes Enable ACL counters";
          }
        }
      }
    }
     }
     }

after I debug, I found when call get_schema() function: it first read yin doc, the yin_doc is correct, it include the " error-message", but after cover to yang doc, the "error-message" is missing. did you meet this issue? could you help on it?

		/* convert YIN to YANG */
		yin_doc = xmlReadDoc(BAD_CAST retval, NULL, NULL, NC_XMLREAD_OPTIONS);
		yang_doc = xsltApplyStylesheet(yin2yang_xsl, yin_doc, NULL);

Thanks,
Jin

**Comment by rkrejci** [comment]
Hi, what version of libnetconf are you using? I just try it with the 0.10.0 version and it works fine. I had to modify your data model (necessary imports are missing), so instead of augment, I have a container in the data model and leafref `fwd-name` also points somewhere else, but error-message is printed - on a separate line:
```
...
          error-message
            "zzxerr:bind this circuit to an interface first before configuring this type of binding.";
          description
            "zzxdes:bind this circuit to an interface first
before configuring this type of binding.";
...
```
but it is printed and neither pyang has any problem with that.

**Comment by classcwnd** [comment]
Hi,

What we are using is 0.9.2, and we found it is caused by yin2yang.xsl. After we uploaded a new yin2yang.xsl from internet in somewhere, it works. 
Is there any difference of yin2yang.xsl between 0.9.2 and 0.10.0?

Thanks,
Yu

**Comment by rkrejci** [comment]
obviously it fixes the yin2yang.xsl issue you have with 0.9.2 ;)

Use the master branch - we are not developing new features on libnetconf and fixing the issues in master, so the master is the most stable and most bugfree version you can get. The master branch is de-facto version 1.0.
