### ISSUE TITLE
libnetconf filter crashing with segmentation fault

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#162]
I'm able to reproduce this crash with this simple example:

Data base is always returning:

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <top xmlns="urn:test:containers:att">
      <container1>
        <container1-id>1</container1-id>
        <container2>
          <container2-id>1</container2-id>
          <name>test</name>
          <container3>
            <att1></att1>
          </container3>
        </container2>
        <container2>
          <container2-id>2</container2-id>
          <name></name>
        </container2>
      </container1>
    </top>

then if I do a get with the filter:

    <top>
        <container1>
            <container2>
                <name></name>
                <conteiner3/>
            </container2>
        </container1>
    </top>

it works fine I get the reply:

    <top xmlns="urn:test:containers:att">
        <container1>
          <container2>
            <name>test</name>
          </container2>
          <container2>
            <name/>
          </container2>
        </container1>
      </top>

but if I use the filter:

    <top>
        <container1>
            <container2>
                <name>test</name>
                <conteiner3/>
            </container2>
        </container1>
    </top>

it crashes in this call: `if (ncxml_filter(doc_merged->children, filter, &node, ds->ext_model) != 0)`

**Comment by michalvasko** [comment]
Hi,
what is the model you are using? If container2 is not actually a list, your data are invalid.

Regards,
Michal

**Comment by ntadas** [comment]
Hi,
container2 is list. 
if you notice the difference between the 2 filters is only a value in the container name.

Regards

**Comment by michalvasko** [comment]
Hi,
I am trying to reproduce your problem, but it is hopeless. I need either the full model you are using or know exactly which nodes are of what type (container2 being a list is not too intuitive...). Thank you.

Regards,
Michal

**Comment by ntadas** [comment]
the problem is that the full model is too big and I cannot put it all here. I've reduce the problem to this small example. I'll think on another way to provide you this.

**Comment by michalvasko** [comment]
So just tell me what each of those node types are. Anyway, you can include files in these issues now.

Michal

**Comment by ntadas** [comment]
ok, here are the types of the nodes (sorry I choose bad names for this example)
top - container
container1 - list
container2 - list
container3 - container
container1-id leaf
container2-id leaf
name  leaf
att1 leaf
