### ISSUE TITLE
Is libnetconf supporting encryption of leaf data if required ?

### ISSUE THREAD

**Issue by BanuPrakashReddy** [CESNET/libnetconf#164]
I have defined a leaf which is of type " ianach:crypt-hash". So I expect, when I configure this leaf using a plain text, it should be stored as encrypted way in data store rather than plain text. 
But, with current implementation it is storing as plain text.

Below is the leaf, I have defined :

leaf password {
                type ianach:crypt-hash;
                must "starts-with(.,'$0$')" {
                  error-message
                   "The password must be sent in the
                    clear text format
                     $0$<clear text password>";
                  description
                    "The password must be sent by the client
                     as clear text.";
  }

Below is the way I have tried to configured:

<password>$0$xyz</password>

Could you please confirm, I libnetconf supports the encryption.

Regards,
Banu Prakash

**Comment by rkrejci** [comment]
The support is not direct. Instead, your transAPi callback associated with the leaf is supposed to do the encryption and rewrite the plain text value by the encrypted value. This approach is used in `ietf-system` where the user passwords are being encrypted - check the [Netopeer's ietf-system example implementation](https://github.com/CESNET/netopeer/blob/master/transAPI/cfgsystem/cfgsystem.c#L885).

**Comment by BanuPrakashReddy** [comment]
Hi,

Thanks for your reply. I tried to follow what has been done in ietf-system password encryption.
But, I am facing a problem with other leafs which has some default values.

Below is the example yang file:
==============================================================
module college {
    namespace "http://www.abc.com/ns/college";
    prefix clg;

   organization
    "TBD";

    revision 2014-09-18 {
        description "Initial revision.";
    }

   container college {

     list awards{
       key name;
       leaf name {
         type string;
      }
      leaf enabled{
        type boolean;
      }
      leaf xyz{
        type boolean;
        default false;
      }
    }
  }
}
================================================================
Here, I want to change the value of  leaf "enabled"  in my transapi to pre described value, which I am successfully able to do.  
But, If I try to configure leaf "xyz" to "false", It is not getting stored in datastore, where as if I configure xyz  as "true". It stores successfully.

In the function "ncds_apply_transapi" before our transapi callbacks are called,  all the default values are getting added and are removed while exiting this function. because false is the default value of "xyz" which I try to configure, it is also getting removed.

Please help me if I am going wrong somewhere.

Below is the configuration:

============================================
<clg:college xmlns:clg="http://www.abc.com/ns/college">
                <clg:awards>
                                <clg:name>ProfileA</clg:name>
								<clg:enabled>false</clg:enabled>
								<clg:xyz>false</clg:xyz>
                </clg:awards>
                
</clg:college>
============================================

Thanks,
Banu Prakash

**Comment by rkrejci** [comment]
Hi, how do you change the xyz's value (I would like to see the actual code)? Do you do it the same way in case of 'false' and 'true' value?

The work with default value is made based on tags - when libnetconf adds the default values, the nodes are tagged by an attribute and when the default values are being removed, all the nodes with this attribute are removed.

**Comment by BanuPrakashReddy** [comment]
Hi,

I do not have any implementation in transapi to change xyz leaf's value. My implementation in transapi is to change  enabled leaf's value, which I am able to successfully do.

I as witten in my previous comment because xyz's default value is false and when I try to configure the same false in my configuration. It is not gewtting added in datastore.
As you rightly said default tags are getting added before calling transapi callback and are removed awhile exiting "ncds_apply_transapi". But while reoving it is also removing configuration of xyz which I have given explicitly.

**Comment by rkrejci** [comment]
Please check that the issue is fixed in the current master branch
