### ISSUE TITLE
nacm error log when NACM not being used

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#166]
Hi,

I have a server implementation that doesn't use NACM.
Every time the server sends a notification the following error log is done by libnetconf:
"nacm_config_refresh: NACM Subsystem not initialized."

in this case this is expected since I'm not using the NACM, would it be possible to change this log from ERROR to DEBUG (or remove it), since its not mandatory to have the NACM enabled to send notifications.

Regards

**Comment by michalvasko** [comment]
Hi,
should be fixed in the master.

Regards,
Michal
