### ISSUE TITLE
unable to connect with latest libnetconf

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#167]
Hi 

everything was working fine until I've downloaded the latest libnetconf (that includes todays fix for nacm + some partial fix for the libnetconf in deadlock during handshake #163)
now I'm not able to connect, the method nc_session_accept_inout always retruns NULL
without changing any of my code but using the old lib everything is working fine.

Regards
Nuno

**Comment by michalvasko** [comment]
Hi Nuno,
is there any error? What may also be relevant, are you using blocking or non-blocking file descriptors for the session?

Regards,
Michal

**Comment by ntadas** [comment]
Hi Michal,

I had the log level to VERBOSE and I didn't saw any error beside the nc_session_accept_inout returning NULL.
The fd that I use in nc_session_accept_inout has the flag O_NONBLOCK set.

Regards
Nuno

**Comment by ntadas** [comment]
I've tried again changing the log level to debug but I don't see any error beside the null return

DEBUG Writing message (session 11): <?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
	............:
DEBUG Received message (session 11): <hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>

ERROR: Session not established

the session not established is my print if the method returns null

Regards
Nuno

**Comment by michalvasko** [comment]
Hi Nuno,
I tried it with a simple server and a client, to connect to each other and it worked fine. Could you perhaps provide your server? I don't know how else to reproduce the issue.

Regards,
Michal

**Comment by ntadas** [comment]
Hi Michal,

ok, I cannot send you my code but I'm able to reproduce the problem using the code in below (it works with the old lib but not with the new one).
please not that in the code below doesn't use any socket you have to write the capabilities in the stdin.

here are the capabilities I've use for this example:
`<?xml version="1.0" encoding="UTF-8"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
</capabilities></hello>
]]>]]>`

the code is here:
`void clb_print(NC_VERB_LEVEL level, const char* msg)
{
    printf("%s\n", msg);
}

int main(int argc, char* argv[])
{
    nc_callback_print(clb_print);
    nc_verbosity(NC_VERB_VERBOSE);

    if (nc_init(NC_INIT_ALL | NC_INIT_MULTILAYER) < 0)
    {
        nc_verb_error("Library initialization failed.");
        return 1;
    }
    struct nc_session *session = nc_session_accept(NULL);
    if(session == NULL)
    {
        clb_print(NC_VERB_WARNING, "Session not established.\n");
    }
    return 0;
}`

Regards
Nuno

**Comment by michalvasko** [comment]
Hi Nuno,
that is quite strange, it is all working fine on my computer. Do you think you could find the commit that is causing the trouble? You would have to try the revisions one by one, but there shouldn't be too much commits.

Regards,
Michal

**Comment by ntadas** [comment]
Hi Michal,

I'll try but just one question, did you compile libnetconf without ssh and
without tls?

Regards
Nuno

**Comment by michalvasko** [comment]
Hi Nuno,
I just did and it still works. Anyway, if you are using file descriptors, SSH or TLS support does not matter, none from those functions are called.

Regards,
Michal

**Comment by ntadas** [comment]
Hi Michal,

found it, it was this commit:
commit 748fb1c605373c58245d41d11ab58baa0adb4350
Author: Peter Nagy <xnagyp01@stud.fit.vutbr.cz>
Date:   Wed Mar 2 13:27:55 2016 +0100

    add with-sessionfiledir configure option

with the commit before this one everything works fine, if I go to this one or any of the next ones I get the issue. Does this help?

Regards
Nuno

**Comment by michalvasko** [comment]
Hi Nuno,
that is quite weird, but try to use the current master. Set the print callback and verbosity (best to debug) before calling `nc_init` and please post the full log here.

Regards,
Michal

**Comment by ntadas** [comment]
Hi ,

I've already done that, I notice this error:
"Opening the sessions monitoring file failed (Permission denied)."

I think this is related with the changes I've mention... just still didn't
understood what is the problem with the paths.

Regards
Nuno

**Comment by ntadas** [comment]
Please note that I'm using DESTDIR in both make and make install commands.
this is necessary since I'm crosscompiling to a different target, I guess
these changes didn't take this in consideration.

Regards
Nuno

**Comment by ntadas** [comment]
probably the problem is here:

src/netconf_internal.h
 @@ -174,11 +174,16 @@
   * libnetconf paths
   */
  #ifdef NC_WORKINGDIR_PATH
 -#  define SESSIONSFILE_PATH  NC_WORKINGDIR_PATH"/libnetconf_sessions.bin"
  #  define NCNTF_STREAMS_PATH NC_WORKINGDIR_PATH"/streams/"
  #else
 -#  define SESSIONSFILE_PATH  "/tmp/libnetconf_sessions.bin"
  #  define NCNTF_STREAMS_PATH "/tmp/streams/"
 +#  define NC_WORKINGDIR_PATH "/var/lib/libnetconf/"
 +#endif
 +
 +#ifdef NC_SESSIONFILE_PATH
 +#  define SESSIONSFILE_PATH  NC_SESSIONFILE_PATH"/libnetconf_sessions.bin"
 +#else
 +#  define SESSIONSFILE_PATH  NC_WORKINGDIR_PATH"/libnetconf_sessions.bin"
  #endif

the NC_SESSIONFILE_PATH is always defined with "" if we don't specify it in the configure line.

Regards
Nuno

**Comment by ntadas** [comment]
Hi Michal,

It seems that NC_WORKINGDIR_PATH and NC_SESSIONFILE_PATH are always defined even when we don't use in the configure (they will stay with "" but defined).
So in the netconf_internal.h the check if both variables are defined will give always true.

Other issue that I see is that I think  NCNTF_STREAMS_PATH  shouldn't depend on the working directory. Since now we have the NC_SESSIONFILE_PATH we should maybe make the /streams/ depend on this path instead.

couldn't it be something like:

`--- a/src/netconf_internal.h
+++ b/src/netconf_internal.h
@@ -178,19 +178,17 @@
 /*
  * libnetconf paths
  */
-#ifdef NC_WORKINGDIR_PATH
-#  define NCNTF_STREAMS_PATH NC_WORKINGDIR_PATH"/streams/"
-#else
-#  define NCNTF_STREAMS_PATH "/tmp/streams/"
+#ifndef NC_WORKINGDIR_PATH
 #  define NC_WORKINGDIR_PATH "/var/lib/libnetconf/"
 #endif

-#ifdef NC_SESSIONFILE_PATH
-#  define SESSIONSFILE_PATH  NC_SESSIONFILE_PATH"/libnetconf_sessions.bin"
-#else
-#  define SESSIONSFILE_PATH  NC_WORKINGDIR_PATH"/libnetconf_sessions.bin"
+#ifndef NC_SESSIONFILE_PATH
+#  define NC_SESSIONSFILE_PATH  NC_WORKINGDIR_PATH
 #endif

+#define SESSIONSFILE_PATH  NC_SESSIONFILE_PATH"/libnetconf_sessions.bin"
+#define NCNTF_STREAMS_PATH NC_SESSIONFILE_PATH"/streams/"
+`

shouldn't the session be coupled with the streams? from my point of view these 2 files could/should be located in /tmp/ by default.
what do you think?

Regards
Nuno

**Comment by michalvasko** [comment]
Hi Nuno,
I don't really see a reason to change the default directory to `/tmp`, that commit was made for a special filesystem, where the sessions file could not be created in `/var`. You can change the path any way you want by defining `NC_WORKINGDIR_PATH`. So, to fix your issue, either change the path to something you have writing access to or start your server as root. The error message is quite clear.

Regards,
Michal

**Comment by ntadas** [comment]
Hi Michal

But the logic inside the lib is wrong. The defines are always defined
during compilation and this makes mandatory the definition of the session
file.
Even if I define it it will not work for me because I is not pressed by
DESTDIR.
The commit that done this change is wrong.

Regards
Nuno

**Comment by michalvasko** [comment]
Hi Nuno,
let's say you define `DESTDIR=/usr`. Nothing prevents you from defining `NC_WORKINGDIR_PATH=/usr/tmp/libnetconf` or anything you want, in this case the sessions file would be saved to `/usr/tmp/libnetconf/libnetconf_sessions.bin`. What is the problem with that?

Regards,
Michal

**Comment by rkrejci** [comment]
You are right Nuno, I'm going to fix it

**Comment by rkrejci** [comment]
Hi Nuno, please try it with the last change in master.

Regarding the `NCNTF_STREAMS_PATH` - it is correct to keep it in working directory. The `NC_SESSIONFILE_PATH` was added due to issues on OpenWRT. We have to move the session file into a filesystem where it is possible to use it as a shared memory. But this location is clean on reboot, so it is not desired to place there streams with event notifications since they would be erased on each reboot.

**Comment by ntadas** [comment]
Hi Radek

Thanks, I'll try it an let you know.

I mix a little 2 topics:
1- the error introduced by the NC_SESSIONFILE_PATH introduction.
2- request/need to move the streams to a different place.

I'll check the first one as mention and give you some feedback.

Regarding the second topic, the reason why I wanted also to move the
streams to a other place is the following:
I'm using the lib in a embedded system, the working_dir is placed in a
persistent part of the memory (in the flash).
the streams will be updated every time we have a notification (e.g. alarms,
database change etc...), I don't want to write to the flash every time we
have these events.
so the idea was to move the streams to a different place (not working dir).
by the way I also notice that if I stop and restart the server without
deleting the streams, the next notifications that I sent are placed in the
stream but the notification actually sent to the client is the first one in
the stream (probably I'm missing something in my implementation, or is this
a bug?)

Thanks
Regards
Nuno

**Comment by rkrejci** [comment]
Is the location, you want to move streams to, persistent? If yes, you can change the working directory.

We will check the thing with notification, but probably it would be great to have the issues separated - could you please create a new issue on this?

**Comment by ntadas** [comment]
Hi Radek, Michal,

Fix works fine, thanks.

the place is would not be persistent, but sure I'll open a new issue and we
can follow up there.

Regards
Nuno
