### ISSUE TITLE
Multiple augments of the same node within a YIN/YANG module are not being processed correctly.

### ISSUE THREAD

**Issue by andre-brizido** [CESNET/libnetconf#171]
Hi 

I detected that multiple augments of the same node within a YIN/YANG module are not being processed correctly.

Example:

```
namespace urn:example
prefix A;

import other-module {
    prefix B;
}

augment "B:parent/B:node1"
   leaf leaf1 {...}
   leaf leaf2 {...}
   leaf leaf3 {...}
   
augment "B:parent/B:node1"
   leaf leaf4 {...}
   leaf leaf5 {...}
   leaf leaf6 {...}
```

   
   
The augmented module only has leaf1,leaf2 and leaf3.
The problem is in the function _update_model in datatastore.c

The following code assumes that the same module only has one augment of the same node per YIN module.

	case 1: /* augment */

				/* check whether this augment was not already resolved */
				for (node_aux = path_node->children; node_aux != NULL; node_aux = node_aux->next) {
					if (xmlStrcmp(node_aux->name, BAD_CAST "augment") == 0) {
						resolved_path = (char*) xmlGetProp (node_aux, BAD_CAST "target-node");
						resolved_ns = (char*) xmlGetNsProp (node_aux, BAD_CAST "ns", BAD_CAST "libnetconf");
						if (strcmp(to_resolve_path, resolved_path) == 0 && strcmp(model_ns, resolved_ns) == 0) {
							free(resolved_path);
							free(resolved_ns);
							break;
						}
						free(resolved_path);
						free(resolved_ns);
					}
				}

				if (node_aux != NULL) {
					/* already resolved */
					break;
				}
            
The following works:

	case 1: /* augment */

				/* check whether this augment was not already resolved */
				for (node_aux = path_node->children; node_aux != NULL; node_aux = node_aux->next) {
					if (xmlStrcmp(node_aux->name, BAD_CAST "augment") == 0) {
						resolved_path = (char*) xmlGetProp (node_aux, BAD_CAST "target-node");
						resolved_ns = (char*) xmlGetNsProp (node_aux, BAD_CAST "ns", BAD_CAST "libnetconf");
						if (strcmp(to_resolve_path, resolved_path) == 0 && strcmp(model_ns, resolved_ns) == 0) {
						   xmlChar* content1 = NULL, *content2 = NULL;

						   //The same module can have multiple augment statements of the same node.
						   //The only way to check if it has already been processed is to check the contents.
						   content1 = xmlNodeGetContent(node_aux);
						   content2 = xmlNodeGetContent(nodes->nodesetval->nodeTab[i]);
						   if (xmlStrcmp(content1, content2) == 0) {
						      xmlFree(content1);
						      xmlFree(content2);
						      free(resolved_path);
						      free(resolved_ns);
						      break;
						   }
						   xmlFree(content1);
						   xmlFree(content2);

						}
						free(resolved_path);
						free(resolved_ns);
					}
				}
				if (node_aux != NULL) {
					/* already resolved */
					break;
				}

I cannot see another way of comparing two augment statements besides comparing the content.

**Comment by rkrejci** [comment]
Hi, could you please add this as a pull-request?

I see the only reason to split the augment - you need different 'when-stmt' in it, am I right? btw, augmenting a specific node from different modules should work correctly.

**Comment by andre-brizido** [comment]
Done the pull request. 
Yes, if it was only one augment from different modules it worked fine.
Actually I got the multiple augment statements because the yang module is divided into sub-modules:

```
module example {

  namespace "example.com";  
  prefix example;

  include sub-module-A;
  include sub-module-B;
  include sub-module-C;
  
  organization 
    "TBD";    
  contact 
    "TBD";  
  description 
    "Example";
  revision 2016-03-18 {
    description 
      "Initial revision.";
    reference
      "TBD";
  }
}

```
So I had to manually merge all sub-modules into a single YIN file in order to use it in libnetconf.

**Comment by michalvasko** [comment]
We will continue in the pull request.
