### ISSUE TITLE
multiple netconf agent instance and single instance of device manager, how to?

### ISSUE THREAD

**Issue by yunyuaner** [CESNET/libnetconf#179]
Hi,

I want to use netconf agent as a SSH "subsystem" service, and ssh server send/recevie netconf message from/to netconf agent via stdin and stdout. A device manager daemon dedicated for managing datastores, and multiple agent work with one single device manager. This approach is the second way to use libnetconf as the document suggested.

However, if I use **ncds_apply_rpc2all** in device manager, "session" and "rpc" structures should be passed from agent to manager, which may involved a method to serialize and de-serialize session and rpc structure, then send them using IPC.

Is my understanding correct? How to implement this approach?

Thanks!

**Comment by michalvasko** [comment]
Hi,
what you described is correct, that is the way it should work (almost all of it is written in the documentation you referred to). This was the architecture [netopeer-server](https://github.com/CESNET/netopeer) used for some time after which we switched to the integrated architecture. The old server is still available in the 0.9.x branch (it works only with *libnetconf* from 0.9.x branch). You can use it directly or just as a reference implementation, but if you decide to use it directly we do not provide support for it anymore.

Maybe [libnetconf2](https://github.com/CESNET/libnetconf2) is also worth mentioning, if you decide to implement a new server. The advantages of using it are new features, [libyang](https://github.com/CESNET/libyang), and full support here on github. The disadvantages are no notifications yet (but they will be added soon) and more importantly, completely missing datastore implementation. We are using [sysrepo](https://github.com/sysrepo/sysrepo) as the datastore. If it did not suit you, you would have to implement datastore on your own.

Regards,
Michal
