### ISSUE TITLE
first time user

### ISSUE THREAD

**Issue by xavierjosephh** [CESNET/libnetconf#183]
Hi,
    I am trying to install Libenetconf can Anyone just let me know of all the dependent packages needed for its installation. Also the steps of installation. It will be a great help if answered. 
I tried installing libssh but for that it said I need cmake and also libssl. I installed cmake and libssl after this when i tried installing libssh, An error was thrown : Delete MakeCache.. but even after its removal I wasnt able to install libssh it gives me the same error.
Hence, I request to kindly tell me the exact procedure to install libnetconf

**Comment by rkrejci** [comment]
1) please RTFM
2) you are describing issues with installing libssh, but you are writing to the libnetconf forum, better ask libssh developers.
