### ISSUE TITLE
install target without doc

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#184]
Hi

currently when we run the install target in libnetconf it always generates the doxygen.

`install: all install-devel install-doc $(INSTALLPYAPI)`

it would be good to have an install target without documentation e.g. install_no_doc

`install_no_doc: all install-devel $(INSTALLPYAPI)`

Regards

**Comment by rkrejci** [comment]
Hi, I have regenerated documentations, so it shouldn't be generated on `make install`. On the other hand, I want to keep it installed, I believe it is an important part of the library and it should be present on the target system.

But I also understand your request. So, by default, all is installed, but there is new Makefile target called `install-bin` which should install only necessary binaries and some other needed files (some XSL stylesheets and so on). 

Please try the current master if it fits to your needs.

**Comment by ntadas** [comment]
thanks a lot , look fine. 
this way I can use the install-bin and install-devel targets for the target installation.

Regards
