### ISSUE TITLE
notifications stream issue

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#191]
Currently in main branch the notification stream is not rotating.
A possible fix is available in a different branch but as far as I know not fully tested and will not go to master branch right?

My understanding is that the notification stream is only needed for the reply notification feature.
Currently I have an issue that my notification stream is growing up to 500 MB :( and I really don't need the reply feature, but I need the notifications.
Is there any possibility to add an option in the libnetconf do disable this stream but keep the notifications? In other words, to keep in the stream only the last notification (always write the notifications from the beginning). 

thanks

**Comment by rkrejci** [comment]
You are right. Now, there is `--disable-ncntf-replay` option for `configure` script to turn off the replay feature (and avoid storing event notifications into files). Please check that it solves your issue.

**Comment by rkrejci** [comment]
The patch is useless, I'm going to revert it.

Actually it seems that it cannot be done this way - the events files are used not only for replay. Storing event record into the file also makes it available for sending it to the clients by `ncntf_dispatch_send()` (in real time, not as part of the replay).

**Comment by rkrejci** [comment]
Currently I have no idea how to implement this without complete reimplementation of netoifications in libnetconf.

**Comment by ntadas** [comment]
ok, thanks.
is it also out of the question to have the file rotation feature in the main branch?
or to have some kind of "truncation" of the file to X MB? e.g. when the file reaches X MB it deletes all the old notifications and start over?

Regards

**Comment by rkrejci** [comment]
I would welcome such features, but I don't have resources to implement it on my own. The rotation feature is available in the `rotating_events` branch, but it has serious issues (see #156) which were not yet fixed by the author so I cannot merge it into the master.
