### ISSUE TITLE
issue when initializing session monitoring

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf#197]
Hi

If we connect two sessions, lest call it "session 1" and "session 2" and disconnect/connect session 1 the offset_next of the session 2 will not point to session 1, this causes a crash when disconnecting session 2.

Scenario: 
- Connect session 1
- Connect session 2
- Disconnect session 1
- Connect Session 1 again
  The nc_session_monitor method first will find the "session 2" as the last session and will find that the new session fits in the gap in the beginning of the list (line 383 session.c)
  The offset_prev offset_next and fist_offset of the new session will be updated but the offset_next of the session 2 will not be updated to 0. This can cause crashes when disconnecting session 2.

Regards

**Comment by michalvasko** [comment]
Hi,
I fixed one problem I found when testing it, but what you are describing does not really make sense, if session 2 is the last connected session, it will always have offset_next 0. Please verify it works for you or provide an exact use-case when something wrong happens.

Regards,
Michal

**Comment by ntadas** [comment]
Hi 

right bad description from my side, sorry. 
the problem was with the offset_prev, this one is used in nc_session_monitor_remove.
I'll test it but from the fix you did this is the problem I was referring to.

thanks a lot.
Best Regards
