### ISSUE TITLE
Libnetconf  User RPC validation 

### ISSUE THREAD

**Issue by urmanyam** [CESNET/libnetconf#198]
Hi,
Can  User RPCS be validated? XML validation of User RPC is not happening. 
Can you please tell if I am missing anything?

**Comment by rkrejci** [comment]
no, libnetconf actually does not validate RPCs automatically. There is some validation (checking) for the basic RPCs, but nothing more.

This functionality is fully implemented in the next generation of the library - in [libnetconf2](https://github.com/CESNET/libnetconf2) and [libyang](https://github.com/CESNET/libyang).
