### ISSUE TITLE
Validation failed for edit-config rpc contain node with mixed prefixes

### ISSUE THREAD

**Issue by SantoshJena** [CESNET/libnetconf#209]
Hi, Valiation failed with netopeer-cli, when a rpc entered with mixed prefixes for edit-config. If I do xml validation with xmllint, this rpc validates correctly.

```xml
<configs xmlns="http://www.ABC.com/ns/yang/ABC">
  <profiles xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">
    <xyz:profile xmlns:xyz="http://www.ABC.com/ns/yang/ABC">
      <xyz:name>A_B</xyz:name >
    </xyz:profile >
  </profiles >
</configs >
```

NETCONF error: operation-failed (application) - Datastore fails to validate (Did not expect element profiles there)

If I add prefixes to all the nodes, like below, it validates correctly. But when it stores into datastore, it doesnot store prefixes for the root node(configs). 

```xml
<xyz:configs xmlns:xyz="http://www.ABC.com/ns/yang/ABC">
  <xyz:profiles xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">
    <xyz:profile xmlns:xyz="http://www.ABC.com/ns/yang/ABC">
      <xyz:name>A_B</xyz:name >
    </xyz:profile >
  </xyz:profiles >
</xyz:configs >
```

Could you please help check it?

Thanks
Santosh

**Comment by michalvasko** [comment]
Hi Santosh,
can you please provide the module for this data?

Regards,
Michal

**Comment by SantoshJena** [comment]
Thanks Michal for your responce. I have added module in a zip file.

[yang.zip](https://github.com/CESNET/libnetconf/files/357102/yang.zip)

Regards
Santosh

**Comment by michalvasko** [comment]
Hi Santosh,
this generation of libnetconf does not support submodules and never will, so that is likely the cause of your problems.

Regards,
Michal

**Comment by SantoshJena** [comment]
ok. Thanks.

**Comment by SantoshJena** [comment]
Hi Michal,
This issue is still valid without submodule. Here I attached models. 

Regards
Santosh
[my-example.zip](https://github.com/CESNET/libnetconf/files/358736/my-example.zip)

**Comment by michalvasko** [comment]
Hi Santosh,
please verify the fix.

Regards,
Michal

**Comment by SantoshJena** [comment]
Hi Michal,

I verified, the rpc is passing now but still you dont store prefixes to the root node. Am I correct ?

Regards
Santosh

**Comment by michalvasko** [comment]
Hi,
yeah, the root node is stored without the prefix for some reason, but the namespaces are generally correct.

Michal

**Comment by SantoshJena** [comment]
Ok. Thanks & Regards,
Santosh.
