### ISSUE TITLE
Libnetconf2 and netopeer2

### ISSUE THREAD

**Issue by joanlandry** [CESNET/libnetconf#212]
Can you tell me the time frame when the next version of libnetocnf and netopeer will be ready?

**Comment by rkrejci** [comment]
It depends what you expects. I believe that we are quite far and it is already usable. However, in comparison to original libnetconf and netopeer we are still missing two big features - NACM and NETCONF Event Notifications. Also support for status data handling (its interconnection with apps providing the status data) was added recently and it is still in development.

I expect, that at the end of 2016 I will be able to recommend moving from Netopeer to Netopeer2 to all users.

**Comment by joanlandry** [comment]
It is not clear to me what is NACM - and I have not found a description of what it does - can you point me to info on what would be the functionality of NACM - thanks you.

**Comment by michalvasko** [comment]
It stands for NETCONF Access Control Model, [this RFC](https://tools.ietf.org/html/rfc6536) describes it.

Regards,
Michal
