### ISSUE TITLE
yin2yang.xsl generates double quote in each statements

### ISSUE THREAD

**Issue by classcwnd** [CESNET/libnetconf#214]
yin2yang.xsl generates double quote in each statements

We found get-schema did not return the correct content, the YANG models returned by the node are not identical to the models released by the Router6672 organization. And the original yang file doesn't contain double quote.
So could you please tell us how to remove the double quote in yin2yang.xsl? 
In particular, they are adding double-quotes around, such as:
-	integer values
-	Boolean values
-	"add" and "not-supported" in deviate statements
Because of the double quote, ENM yang transformer failed to transform the models.

Example:
```
  deviation "/if:interfaces/if:interface" {
    deviate "add" {
      must "if:type != 'ianaift:ipForward' or ifxipos:l3-interface" {
Cannot create RFC 7223 interface for L3without creating child l3-interface        description
          "Cannot create RFC 7223 interface for L3without creating child l3-interface";
      }
    }
```

```
  import "ietf-interfaces" {
    prefix "if";
  }
```

**Comment by michalvasko** [comment]
Hi,
it is possible there are some syntactic differences, but there should not be any semantic ones. Therefore, if any YANG parser has trouble parsing these modules, it is its fault. The quotes are required in some cases and the simplest way to cover them is to add quotes everywhere, correct parsers must treat these values in the same way. Nevertheless, if you really want to change this behavior, you are free to modify the schema for your purposes. I hope you do not expect us to explain XML Schema to you.

Regards,
Michal
