### ISSUE TITLE
Question regarding datastore having multiple top level nodes

### ISSUE THREAD

**Issue by pd45169** [CESNET/libnetconf#215]
Hi,

I am currently implementing ietf-ptp-dataset and found it has direct list under module without any container. So transapi should return configuration data with multiple nodes in a xmldoc. What should be the root of such module ? I tried to put the nodes within <data></data>. But it did not work. Libnetconf is putting all the content along with <data> in datastore.xml file.

Does libnetconf support such model ?

**Comment by michalvasko** [comment]
Hi,
it seems libnetconf supports this to certain limited extent meaning the model can be parsed (even this was not possible some long time ago). However, we do not work with such models and so it seems there are some things missing for it to work properly.

You can look into it and we will accept a pull request that will fix it, but we are busy working on libnetconf2 (which can handle models with more top-level elements without problems) and related tools. We will not add any new features to libnetconf.

Regards,
Michal
