### ISSUE TITLE
Uploading Config File using NETCONF

### ISSUE THREAD

**Issue by virajmistry** [CESNET/libnetconf#216]
Hi Michal

I am referring NETCONF protocol document and i came to know that NETCONF is capable of uploading Config file on one go.(i.e i can configure my device using NETCONF protocol by just one config file).
I have already created my custom yang file using TransAPI example and its is also working fine.
But now want to use this feature in my module how can i do this ?
Is there any good example on it ?

Please provide your view for the same.

Regards,
Viraj

**Comment by rkrejci** [comment]
What do you mean by uploading config file - `copy-config` NETCONF operation? Then the code in TransAPI module should work the same way as for `edit-config`. The complete tutorial for TransAPI is available [in the libnetconf documentation](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html) and example code is available at the [Netopeer's transAPI directory](https://github.com/CESNET/netopeer/tree/master/transAPI)

**Comment by virajmistry** [comment]
Hi,

Thank you for reply.

Yes i was talking about Copy-Config.
We want to copy all the config using SCP to other location.
However we have changed code and now its working.

Thanks
Viraj
