### ISSUE TITLE
Receiving Notifications when in middle of receving reply chuunks for GET request

### ISSUE THREAD

**Issue by parkrish** [CESNET/libnetconf#221]
I guess, the libnetconf can receive notifications in the middle of receiving chunks of reply for the GET request for the same session.Please confirm.

When using libnetconf as Netconf client, do we need to advertise the notification and interleave capabilities in order to receive notifications in the middle of get/edit operations ?

**Comment by rkrejci** [comment]
I don't know how this could be done - [RFC 6241](https://tools.ietf.org/html/rfc6242#section-4) states, that NETCONF peers exchange **complete** XML documents. How the peers could know that one chunk belongs to a rpc-reply message while another one belongs to a notification?

**Comment by parkrish** [comment]
Thanks for the information.
Please clarify on the second part of the question.
Does the libnetconf client be advertising the notification and interleave capabilities in order to support interleaving or is it fine if only the server advertise it ?

**Comment by rkrejci** [comment]
It is the server capbility, client is not supposed to advertise anything but NETCONF base capability (1.0 or 1.1). But you were asking about "receive notifications in the middle of get/edit operations" and that is not possible even with the interleave capability. No server can do what you are asking about. Interleave capability is about sending notification between two rpc-replies, not inside (between chunks of) one rpc-reply.

**Comment by parkrish** [comment]
Thanks for the clarification and thanks for your time.

Best regards,
Paramesh
