### ISSUE TITLE
How to generated *.xxd for yang/yin models?

### ISSUE THREAD

**Issue by classcwnd** [CESNET/libnetconf#229]
Hi,

How can we generated *.xxd file by yang/yin model?
We need to updated them.

Thanks,
Yu

**Comment by rkrejci** [comment]
Hi, can you share with us which of the internal modules are supposed to be updated?

**Comment by classcwnd** [comment]
Hi, 
we need to update ietf-inet-types, and we just found you have updated it in latest code. That's fine.
Can we updated them by ourselves and how is the way?

**Comment by rkrejci** [comment]
You can use `xxd` utility with `-i` option.

**Comment by classcwnd** [comment]
hi!

Could you please share us where the xxd utility is?
Thanks!

**Comment by rkrejci** [comment]
Did you try to google it? It is quite common utility of Linux distros, on my OpenSUSE it is part of the `vim` package.
