### ISSUE TITLE
support for yang 1.1

### ISSUE THREAD

**Issue by jayganatra** [CESNET/libnetconf#231]
Does libnetconf supports action statement given in RFC 7950 ?

https://tools.ietf.org/html/rfc7950#section-7.15

**Comment by michalvasko** [comment]
Hi,
no, libnetconf does not and never will support any YANG 1.1 features. However, our new generation of tools ([Netopeer2](https://github.com/cesnet/netopeer2) and its libraries) should start supporting all YANG 1.1 features in the upcoming months.

Regards,
Michal
