### ISSUE TITLE
Failed to add session to poll context

### ISSUE THREAD

**Issue by frahmanu** [CESNET/libnetconf#238]
I have a netconf server which listens on port 830, and accept client connection and process RPC. 
For first session nc_ps_add_session() is successfull and session is added to the poll context, but nc_ps_add_session() is failing always with timeout error for second session.

SESSION 1 :

New incomming session -->
Received Hello message from client. Adding session to poll context.
Successfully added a new session to poll context.

SESSION 2:
New incomming session
Received Hello message from client. Adding session to poll context.
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
Failed to add new session to poll context. Clossing SSh session.

**Comment by michalvasko** [comment]
Hi,
please close this issue and create it in libnetconf2 issue tracker, it is not related to libnetconf, thank you.

Regards,
Michal
