### ISSUE TITLE
i am confused to choose libnetconf or libnetconf2 ,can you list the features which libnetcnf2 support now? thanks!

### ISSUE THREAD

**Issue by RogerYaozhenyu** [CESNET/libnetconf#246]

**Comment by rkrejci** [comment]
Hi, I have updated the [libnetconf2 README in the devel branch](https://github.com/CESNET/libnetconf2/blob/devel/README.md), check the section `libnetconf vs libnetconf2` which should help you.

**Comment by RogerYaozhenyu** [comment]
thanks for your feedback so quickly, i have some question want to konw clearly ,  there is no mention about 
the Confirmed Commit Capability ,Rollback-on-Error Capability,XPath Capability and yang-push:1.0 etc, 
so i want to know that does the ibnetconf or libnetconf2 supoort these features?  thanks
