### ISSUE TITLE
YANG "submodule" support - is it planned in libnetconf

### ISSUE THREAD

**Issue by kisyan89** [CESNET/libnetconf#247]
Hi
I want to know if YANG "submodule" statement is planned to be supported by the core team.
I understand it's not quickly solved issue, but what if it's not even planned. So I just want to clarify.

Besides, maybe
somebody can suggest some kind of workaround for "submodule" support within libnetconf.

It would be highly appreciated.

**Comment by rkrejci** [comment]
Hi, definitely no, YANG submodules are already implemented in libyang used by libnetconf2.

The only workaround is probably to modify the YANG module and submodules to be in a single module.
