### ISSUE TITLE
Is ietf-netconf-server.yang most up to date?

### ISSUE THREAD

**Issue by psykokwak4** [CESNET/libnetconf#263]
Hi,

I found `models/ietf-netconf-server.yang` is based on YANG model drafted [here](https://tools.ietf.org/id/draft-kwatsen-netconf-server-01.html). And the entity name `&quot` for HTML escaped character `"` is used in the [comment](https://github.com/CESNET/libnetconf/blob/a7fece94d411a346e05e04977e6e81048ea0a5c0/models/ietf-netconf-server.yang#L362) for this YANG model.

I tried to search in [openconfig](https://github.com/openconfig/public) and [yang](https://github.com/YangModels/yang) repository but found no `&quot`.(and the `ietf-netconf-server.yang` with same revision showed in the commit history is different from this one). Just want to know if it is safe to replace `&quot;` with `"` in YANG model.

Thanks so much!

**Comment by rkrejci** [comment]
There should be probably `\"`, but the model itself is not directly used in libnetconf (it supports only the YIN format of the schemas).
