### ISSUE TITLE
 libnetconf only support subtree filter ,not xpath fliter?  

### ISSUE THREAD

**Issue by zyboy2000** [CESNET/libnetconf#265]
filter xmlns:t="http://example.com...."
          type="xpath"
          select ="/t:top/t:name['fred']"/

i send this rpc ,return error  ,follow code , find netconf.h

typedef enum NC_FILTER_TYPE {
   NC_FILTER_UNKNOWN,
   NC_FILTER_SUBTREE
}NC_FILTER_TYPE

so libnetconf only support subtree filter ,not xpath fliter?  libnetconf2 support all

**Comment by rkrejci** [comment]
correct

**Comment by zyboy2000** [comment]
but libxml2 has xpath fuction，why not support？if i want xpath fuction，only change to libneconf2？no others way？

**Comment by michalvasko** [comment]
Just because *libxml2* supports XPath on XML, it does not mean it is simple to implement it for YANG data. So yeah, switch to *libnetconf2* or perhaps send us a patch that adds XPath support for *libnetconf*, I see no other way.

Regards,
Michal
