### ISSUE TITLE
I suggest send hello msg in multi-line

### ISSUE THREAD

**Issue by chengdingshan** [CESNET/libnetconf#266]
current the netconf2 server will send hello msg just in one line, it is bad for human read.
eg.
`<hello xmlsns=...><capabilities><capability>...</capability><capability>...</capability><capability>...</capability><capability>...</capability><capability>...</capability><capability>...</capability><capability>...</capability><capability>...</capability> ...`

I suggest it print in well-formed multi-line
`<hello>`
` <capabilities>`
`  <capability>...</capability>`
`  <capability>...</capability>`
`  <capability>...</capability>`
`  <capability>...</capability>`
`...`

**Comment by rkrejci** [comment]
you can format it by other tools, the message is designed for machine processing and avoiding formatting bytes save transport line. By the way, you are talking about netconf2 server, but this is libnetconf project issue tracker which has nothing to do with netconf2 server.
