### ISSUE TITLE
My netconf server in function nc_session_recv_rpc always return 0, rpc is NULL

### ISSUE THREAD

**Issue by UnknowSelf** [CESNET/libnetconf#267]
My netconf server is the subsystem of SSH
workflow:
```
  nc_init()
  ncds_new_transapi()
  ncds_file_set_path()
  ncds_init()
  ncds_consolidate()
  ncds_device_init()
  nc_session_accept()
  loop{
     nc_session_recv_rpc()
     ...
  }

```

I used netopeer-cli test connect. See the log, I can find that sever and client send hello message each other, but in the server, The function **_nc_session_recv_rpc_** always return 0 (NC_MSG_UNKNOWN), and the sessio was closed.

Log:
```
  nc_session_read_until: reading limit reached.
  Malformed message received, closing the session 1.
  nc_msg_dump: invalid input parameter.
  rpc: (null)
```
  How can I do?
  Thanks!

**Comment by UnknowSelf** [comment]
@rkrejci @alexadavid @michalvasko

**Comment by michalvasko** [comment]
Hi,
just guessing, but it may be some incompatibility in your `hello` messages, perhaps the server expect one NETCONF version communication, but the client uses another. I cannot help you more, *libnetconf* is obsolete and so we provide only basic support.

Regards,
Michal
