### ISSUE TITLE
notifications not working netopeer-server and netopeer-cli

### ISSUE THREAD

**Issue by dileepravindran** [CESNET/libnetconf#268]
I'm trying to test the generic notification from netopeer-server to netopeer-cli.

Currently i was able to set up netopeer-server and netopeer-cli and establish a session and make subscribe request  from  netopeer-cli .

i'm trying to send a generic notification by following the thread 

https://github.com/CESNET/libnetconf/issues/170

i can  see the notification added to NETCONF.events file successfully  but not showing up on netopeer-cli prompt.

Could you please help me with some suggestion why this might be happening or if i'm missing anything here.

Thank
Dileep

**Comment by michalvasko** [comment]
Hi Dileep,
please do not use this old software, in [libnetconf2](https://github.com/cesnet/libnetconf2) everything should work.

Regards,
Michal

**Comment by dileepravindran** [comment]
Thanks for the quick reply .

Can you provide me with example for generic notification with netopeer2 server client

**Comment by michalvasko** [comment]
Sure, just connect with one client, subscribe, and connect with another client. The first client should get notified about a new session.

Regards,
Michal

**Comment by dileepravindran** [comment]
hi michalvasko ,
  I'm receiving session notification. i do not see any issue there .

My query is , if there is a sample code in which we can send a generic event notification to the client just as done with netopeer server client as explained in 
https://github.com/CESNET/libnetconf/issues/170

Thanks

**Comment by michalvasko** [comment]
Let's move the discussion to libnetconf2.
