### ISSUE TITLE
Libnetconf  0.9.0 configuration error in yocto Pyro

### ISSUE THREAD

**Issue by AmitGondaliya** [CESNET/libnetconf#269]
Hi All,

I am compiling the libnetconf 0.9.0 in yocto pyro 2.3 version, but at the time of configuring libnetconf in yocto I got below error.

**checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for ELF visibility... yes
checking for xml2-config... yes
**ERROR: /usr/bin/xml2-config should not be used, use an alternative such as pkg-config
ERROR: /usr/bin/xml2-config should not be used, use an alternative such as pkg-config**
checking for xmlDOMWrapReconcileNamespaces in -lxml2... no
checking for xslt-config... yes
**ERROR: /usr/bin/xslt-config should not be used, use an alternative such as pkg-config
ERROR: /usr/bin/xslt-config should not be used, use an alternative such as pkg-config**
checking for xsltApplyStylesheet in -lxslt... no
configure: error: Missing libxslt library**

We have already libxslt and libxml2 installed.

As per log, Build system suggests to replace with xml2-config and xslt-config with pkg-config. However we dont know what will  be the consequence if we do that.

Can the xslt-config and xml2-config replace by pkg-config ? if yes then please let us know from where we can start this activity and is it safe ?
If any new package is available with pkg-config of Libnetconf then kindly let us know.

Please help us in this matter.

Regards,
Amit G

**Comment by michalvasko** [comment]
Hi Amit,
there is a new package available, [libnetconf2](https://github.com/cesnet/libnetconf2). Support for *libnetconf* is over, either try to solve your problems without our help or use the new generation of tools.

Regards,
Michal

**Comment by AmitGondaliya** [comment]
Hi Michal,

Thanks for your valuable suggestion.

Is there any demo for the Trans API application available for libnetconf2 through which reference I can develop my own use case/ Trans API module.

thanks In advance 

Best Regards,
Amit G

**Comment by michalvasko** [comment]
Hi,
when using the new tools, your primary interest becomes [sysrepo](https://github.com/sysrepo/sysrepo). It includes documentation and examples, I suggest you start there.

Regards,
Michal
