### ISSUE TITLE
configure: error: Missing the libssh_threads library.

### ISSUE THREAD

**Issue by andrei-pavel** [CESNET/libnetconf#273]
On `./configure`, I get `configure: error: Missing the libssh_threads library.`.

Note that this is not `libssh` which I have at the latest version:
```
extra/libssh 0.8.2-1 (186.1 KiB 614.0 KiB) (Installed)
    Library for accessing ssh client services through C libraries
core/libssh2 1.8.0-2 (180.2 KiB 346.0 KiB) (Installed)
    A library implementing the SSH2 protocol as defined by Internet Drafts
```

This seems to be a biproduct of earlier versions of `libssh`. While looking for answers, I've found the following `libssh 0.8 supports threading, and the specific libssh_threads.so library has been dropped. Packages go to staging` on the TODO page of ArchLinux (https://www.archlinux.org/todo/).

Would you update to the latest `libssh` version?

**Comment by mentalibor** [comment]
The same thing happened to me on Ubuntu 18.04.01! Hope someone will update the libssh as soon as possible! :)

**Comment by andrei-pavel** [comment]
Well, to be fair and not too pedantic on your wording, action seems to be required on the `libnetconf` side. What I suggested was that they update to the latest `libssh` version in the form of support for `pre-0.80` versions and `post-0.80` versions separately as now only `pre-0.80` versions are supported.

**Comment by mentalibor** [comment]
You are actually right, because I have tried many different versions of libssh and always the same scenario happens: when I run command `./configure`, it says 'configure: error: Missing the libssh_threads library.'

**Comment by michalvasko** [comment]
Hi,
it should work now also with libssh version 0.8.0 and newer. However, it is already long past *libnetconf* support has finished so you should have been using [libnetconf2](https://github.com/cesnet/libnetconf2).

Regards,
Michal
