### ISSUE TITLE
Does libnetconf and sysrepo support netconf time capability

### ISSUE THREAD

**Issue by Maku-chan** [CESNET/libnetconf#283]
Hello,

I have a device which is already working as a netconf server with the sysrepo as the datastore and libnetconf for the netconf communication. I want to know is it possible to support the following capability:

urn:ietf:params:netconf:capability:time:1.0

As i want to send configuration commands with scheduled time for the execution of the commands.

Thanks.

Kind regards,
Maku_chan

**Comment by michalvasko** [comment]
Hi,
no, this experimental feature is not supported and there is no plan to. Actually, this is the first time I hear about it.

**Comment by Maku-chan** [comment]
Hi,

Thanks a lot. I just want to ask that is there any feature in netconf where I can schedule a commit in the future on the device.

Kind regards,
Maku_chan

**Comment by michalvasko** [comment]
No, there is no such functionality available.

**Comment by Maku-chan** [comment]
Thanks a lot
