### ISSUE TITLE
Information - Which API is responsible for sending Server Hello to netconf client during TLS handshake?

### ISSUE THREAD

**Issue by rc1997258** [CESNET/libnetconf#290]
Hi, 
There was a need to manually manipulate the libnetconf/netopeer/sysrepo library, so that, during a TLS handshake to establish a new netconf session, when the client sends "client hello" message, I need the server to not respond with "Server Hello" and further process, at least intend to introduce a sleep time (5 minutes). 
Could anyone please tell me which library and API should I look into? from libnetconf/netopeer/sysrepo?

Thanks in advance!

**Comment by michalvasko** [comment]
You have mentioned *sysrepo*, which *libnetconf*/*netopeer* are not even using so I am going to assume you meant *libnetconf2*/*netopeer2*. This code is then found in *libnetconf2*.

**Comment by rc1997258** [comment]
Thank you very much!

Can you also please tell me, would it be possible to configure a TLS handshake timeout in libnetconf2? 
Would this timeout work in the below case?
When the TLS handshake start between client and server, with reference to netconf.
When the client sends "client hello" to server, and server does not send "server hello", here the actual network frames are getting dropped, due to a problem in the physical hardware. I need the timeout to work in this scenario.

Can you please tell me if there is such configuration present in libnetconf 2?
Thanks!

**Comment by michalvasko** [comment]
[Here](https://github.com/CESNET/libnetconf2/blob/master/src/session.c#L1453) is the function with `hello` timeout of the server, can be configured for standard sessions (`idle-timeout` is found in the YANG configuration). Server Call Home and client (function above) `hello` timeout are compile-time constants.

**Comment by rc1997258** [comment]
Thanks for this information, this answered my question.

Can you please tell me, if there is any caching mechanism in sysrepo ? or netopeer1 / netopeer2-server ?

I was also debugging a possible memory leak in the proprietary software which uses sysrepo (version 1) to store and emulate all the netconf related configurations.
Whenever I try to fetch a related configuration through restconf request, a new netconf session would be created to connect to sysrepo through netopeer(not sure if this is really used). I see there is a memory increment in the main process, which is using sysrepo as a library.

And when I use Valgrind tool to check if there is really a memory leak, it did not show any possible memory leaks, but there was still some memory being used when the process was ended. The examply valgrind output was as below - 

==2420== HEAP SUMMARY:
==2420==     in use at exit: 2,240 bytes in 81 blocks
==2420==   total heap usage: 82 allocs, 1 frees, 2,592 bytes allocated
==2420==
==2420== LEAK SUMMARY:
==2420==    definitely lost: 0 bytes in 0 blocks
==2420==    indirectly lost: 0 bytes in 0 blocks
==2420==      possibly lost: 0 bytes in 0 blocks
==2420==    still reachable: 2,240 bytes in 81 blocks

Here, there was only still reachable memory being used, and this was increasing everytime a new netconf session was created. When the old netconf session was freed, this memory was not released back to the OS.


Could you please tell me, would this be a memory leak in the sysrepo library? If it is, can you please tell me, where I can try to look at?

**Comment by michalvasko** [comment]
Yes, there is data caching in *sysrepo*/*netopeer2-server* but all the data are freed when the connection is destroyed, on server termination. Please do not ask me about *netopeer*, which is deprecated and not supported.

**Comment by rc1997258** [comment]
Here, server termination in the sense, that whole sysrepo/netopeer-2 library instances are terminated?
Is there any other way to manually free the cache? and also could you please point me towards the API's which are responsible for caching, and freeing the cached memory?

This would be my final infromation gathering for this ticket.

For some reason, for every new netconf session to sysrepo, I see a memory increment, but when this netconf session is freed, this cache is not cleared, this is eventually leading to complete RAM utilization.

**Comment by michalvasko** [comment]
Termination in the sense that the `netopeer2-server` binary is terminated. *sysrepo* is just a library. You cannot manually free the cache, it is in the `netopeer2-server` process. Also, the cache is in the **connection**, not **session** so whatever memory increment you see, it is not because of data caching. But you are talking about NETCONF sessions, which include much more than just a *sysrepo* session. Go through the *netopeer2* code to find out more.

**Comment by rc1997258** [comment]
there is nc_callhome_accept_session in libnetconf1, if a new callhome session gets stuck in this API, due to a problem in TLS handshake, would this affect other network communications?

Because, in our software, we also use ZMQ REQ-REP pattern, for communication between server and client. The netconf session is happening at the server.
During this stage, if a new netconf session gets stuck during the TLS handshake stage, there is a problem observed at the ZMQ communication as well, that is client is able to send messages to server, but the server is not able to see them at all (messages are getting lost!).

Since the TLS handshake is also processed inside the API - nc_callhome_accept_session(), the call to this API would block until the TLS handhsake gets completed.
This blocking behavior is affecting the ZMQ communication as well!

Could you please tell me, what could cause this behavior from the libnetconf1 library? the API is - "nc_callhome_accept_session".

Thanks!

**Comment by michalvasko** [comment]
No, sorry, I cannot help you and sinece *libnetconf* is not supported for many years now, I will not spend time finding out, you will have to.

**Comment by rc1997258** [comment]
Its totally fine, Thanks a lot!
