### ISSUE TITLE
libnetconf data model

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CESNET/libnetconf#38]
```
Feature description:

Create YANG data model implemented by the library with its own enhancements.

As first, libnetconf now generates notifications on datastore lock/unlock. The 
notification is under "urn:cesnet:params:xml:ns:libnetconf:notifications " 
namespace. The data model will be announced by the libnetconf-based servers in 
<hello> messages.
```

Original issue reported on code.google.com by `rkre...@cesnet.cz` on 27 May 2014 at 12:03

**Comment by ntadas** [comment]
Is there any expected date when will the model for the datastore lock/unlock be available?
or is it possible somehow to disable these notifications?
I'm asking this because some clients (ODL) complain about these notifications since they are not announced.

**Comment by michalvasko** [comment]
Hi,
these notifications will never be supported by libnetconf, its development is finished, we are only doing bugfixes. It may appear in the new generation of our tools, but even if, it will not be soon.

regards,
Michal

**Comment by ntadas** [comment]
Hi

Why do you way they are not supported? In the current libnetconf the lib is sending these notifications and they are not announced as capabilities, this is not a correct behaviour.

Regards

**Comment by ntadas** [comment]
Thanks a lot for fixing this issue
I still have one question, why are these notifications needed? They are not standard right?
