### ISSUE TITLE
libnetconf cross compile for powerpc

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/libnetconf#64]
Hi,
I want to build libnetconf on powerpc.
I configure 
./configure --disable-libssh2 --host=powerpc-my-linux-gnu --with-sysroot=/var/powerpc-my-linux-gnu --prefix=/root/libnetconf-dependency/target/libnetconf

After build to some error.
I need to build some additional libraries:
libxml2-2.9.1
libtermcap 2.0.8
libxslt-1.1.28
.......

[root@CentOS-6 libxml2-2.9.2]# ./configure --disable-static --with-history --host=powerpc-my-linux-gnu

.....
checking for sscanf... yes
Disabling code coverage for GCC
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating libxml2.spec
gawk: error while loading shared libraries: libtermcap.so.2: wrong ELF class: ELFCLASS32
config.status: error: could not create libxml2.spec

**Comment by JackLIN-F** [comment]
Hi,
I build libxml2-2.9.1 library.
Need I build python??

**Comment by rkrejci** [comment]
IMO you have problem with building libxml2, not libnetconf. So you are asking questions at wrong place.
