### ISSUE TITLE
Multiple aument to the same target node fail

### ISSUE THREAD

**Issue by kevinlinl** [CESNET/libnetconf#68]
Hi,
Here I have one question about libnetconf. 
I tried to augment a container (in A yin file), and a list (in B yin file) to the same XPATH at the same time. And I found it only support on or another at a time, which means one will cover another.
Could it be possible that libnetconf doesn’t support two YINs file to augment to the same XPATH ?

-----------------------------
R:Router

Yin file A,  augment “R:Router” {
    Container container1 …

Yin file B, augment “R:Router” { 
   List list1 …
-----------------------------

The code in function "_update_model" in datastore.c seem cause this issue.
if (strcmp(to_resolve_path, resolved_path) == 0) {         
  free(resolved_path);  
  break;
}  

Could you please have a check ?
Thank you very much.

**Comment by michalvasko** [comment]
Hi,

thanks for a detailed bug report, it should be fixed now.

**Comment by kevinlinl** [comment]
Hi,
Thank you so much for the quick fix.
