### ISSUE TITLE
--disable--libssh in document

### ISSUE THREAD

**Issue by warvyvr** [CESNET/libnetconf#69]
in the page 'Compilation and Installation‘ of documentation
it describes as following:
--disable--libssh
Remove dependency on the `libssh` library. By default, the `libssh` library is used by the client side functions to create SSH connection to a remote host. If the usage of the `libssh` is disabled, libnetconf will use a standalone `ssh(1)` client located in a system path. `ssh(1)` client is, for example, part of the OpenSSH. This option has no effect for server-side functionality.

I suppose --disable--libssh is a typo, it should be --disable-libssh, there is a single hyphen between 'disable' and 'libssh'

**Comment by michalvasko** [comment]
Yep, it is a typo and will be fixed the next time the documentation is regenerated, it is quite obvious.
