### ISSUE TITLE
Question for supporting "deviation" statement

### ISSUE THREAD

**Issue by kevinlinl** [CESNET/libnetconf#70]
Hi,
We want to support ‘deviation’ in Libnetconf. After analyzing the related source code, to support it, we think two parts of code should be modified:
1.	In function ncds_consolidate(void), add code to handle the “deviation”, similar with the “augment”.  Firstly, find out all the deviation definitions. Then update them to internal model(datastore->ext_model);
2.	Announce the deviation capability and the deviation modules in hello message.

Is my understanding right? Are there anything else I missed? Thanks a lot.

Best Regards

**Comment by rkrejci** [comment]
Hi, I believe you are right. Point 2 should be handled somehow automatically - when the deviating module is loaded, it is kept by libnetconf in kind of internal list from which it then generates the capabilities list. Point 1 will be the main work.

BTW, I'm finishing deviation support in my other project, libyang. So, deviation will be supported in next libnetconf generation. Anyway, I would appreciate your patches for the current libnetconf.
