### ISSUE TITLE
Questions for supporting "if-feature"

### ISSUE THREAD

**Issue by jinxud** [CESNET/libnetconf#71]
Hi,
We want to support ‘if-feature’ in Libnetconf. After verify and analyzing the related source code, I have 2 questions

1. in ncds_update_features() will call feature_check(node, datastore->data_model->features) with base model's features. seems it does not handle the augment models. for example: for ospf model, the base model is config model. there is feature definition in ospf model but not in base model. so here, the datastore->data_model->features is empty. then if the feature is disable, the node is not removed, the function still can be confiugred. could you help confirm?

2. parse_model_cfg

name = strdup(basename(model_path));
	/*cut off the .yin suffix */
aux = strrchr(name, '.');

if the model files is like this. config@2015-06-25.yin. the name will be config@2015-06-25
then will call ncds_feature_enable(name, feature). but in models_list, the model name is without date. which will cause cannot find the model, and update the feature status failed. 

Is my understanding right? Thanks a lot.

Thanks,

**Comment by rkrejci** [comment]
ad 1 - you are right, I'll try to fix it
ad 2 - you are probably again right, but at the wrong place. parse_model_cfg is part of netopeer, not libnetconf.

Could you please share a link to the data models (ospf) I could use to test the fix for issue 1?

**Comment by jinxud** [comment]
hi,

thanks for your quick update. it seems I am not able to upload the model file.

for the issue 2. could you explain a little bit?

**Comment by jinxud** [comment]
for the issue2, I use gdb to investigate. in function parse_model_cfg(), the name is with date, and then call ncds_feature_enable(name, feature). in ncds_feature_enable, it will find model with name, but in models_list, the model name is without date. so it failed. my understanding is not correct?

**Comment by rkrejci** [comment]
:) actually for 2 I have already a patch, but this is issue tracker for libnetconf, not Netopeer. Netopeer has a separate issue tracker at https://github.com/CESNET/Netopeer/issues. I'm not able to connect fix in Netopeer source code with the issue in libnetconf project.

**Comment by rkrejci** [comment]
point 2 is fixed in Netopeer master branch and described as issue 33 in netopeer issue tracker.

**Comment by rkrejci** [comment]
back to point 1, the referenced commit in master should fix what you described here, please test.

But as mentioned in commit message, there is still issue with using features from another module (via import). With current implementation, it is to complicated to solve the problem, so we will wait with the complete solution for the future use of libyang instead of libxml2.

**Comment by jinxud** [comment]
hi

I test your fix, but it does not work for augment model.  in ncds_update_features(), 
if (!xmlStrcmp(node->name, BAD_CAST "augment"))  -> it always false. seems it cannot find augment. but I printout the datastore->ext_model, there is augment, and ospf model is augment. 

could you help confirm?

Thanks

**Comment by rkrejci** [comment]
I'm not able to confirm the problem without data models - you will have to share them. You can store it somewhere on a server and just put links to them here.

**Comment by rkrejci** [comment]
Comment from #72 gave me a clue, please test it now.

**Comment by jinxud** [comment]
hi,

I verify the fix, unfortunately, it still does not work. the node->children is empty. so  in feature_check, it does not do any recursion check. shall we check the node->next first? could you explain a little bit for what content is node->children? what is node->next?

(gdb) p node->children
$16 = (struct _xmlNode *) 0x0
(gdb) p *node
$17 = {
  _private = 0x0, 
  type = XML_ELEMENT_NODE, 
  name = 0xa265f0 "yang-version", 
  children = 0x0, 
  last = 0x0, 
  parent = 0xa1ff20, 
  next = 0xa26740, 
  prev = 0x0, 
  doc = 0x91a5b0, 
  ns = 0xa23400, 
  content = 0x0, 
  properties = 0xa26610, 
  nsDef = 0x0, 
  psvi = 0x0, 
  line = 3, 
  extra = 0
}
(gdb) p * node->next
$18 = {
  _private = 0x0, 
  type = XML_ELEMENT_NODE, 
  name = 0xa267c0 "namespace", 
  children = 0x0, 
  last = 0x0, 
  parent = 0xa1ff20, 
  next = 0xa25e30, 
  prev = 0xa26570, 
  doc = 0x91a5b0, 
  ns = 0xa23400, 
  content = 0x0, 
  properties = 0xa267e0, 
  nsDef = 0x0, 
  psvi = 0x0, 
  line = 4, 
  extra = 0
}


Thanks

**Comment by rkrejci** [comment]
node->children is for children and node->next is for siblings. It doesn't make sense to use next in this case since there is for loop for children where all children are processed. When children pointer is NULL, there is no children so no need for feature_check() on next level of the XML tree.

**Comment by jinxud** [comment]
I test it again. now the result is when disable the feature, the rpc-reply is ok, but the configuration does not apply to the node.

according the rfc: 
If data for a node tagged with "if-feature" is present, and the
feature is not supported by the device, the server MUST reply with
an "unknown-element" error-tag in the rpc-error.

below is the rpc message:

<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability>
    <capability>urn:ietf:params:xml:ns:yang:ericsson-ethernet?module=ericsson-ethernet&amp;revision=2015-06-25</capability>
    <capability>urn:ietf:params:xml:ns:yang:ericsson-interface?module=ericsson-interface&amp;revision=2015-07-03</capability>
    <capability>urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&amp;revision=2014-05-08</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-interfaces?module=ietf-interfaces&amp;revision=2014-05-08</capability>
   <capability>urn:ietf:params:xml:ns:yang:ericsson-ospf?module=ericsson-ospf&amp;revision=2015-06-25</capability>
    <capability>urn:ietf:params:xml:ns:yang:IP-FORWARD-MIB-state?module=IP-FORWARD-MIB-state&amp;revision=2006-02-01</capability>
    <capability>urn:ietf:params:xml:ns:yang:ericsson-bgp?module=ericsson-bgp&amp;revision=2015-07-08</capability>
    <capability>urn:ietf:params:xml:ns:yang:bgp-state?module=bgp-state&amp;revision=2015-05-10</capability>
    <capability>urn:ietf:params:xml:ns:yang:ericsson-mpls?module=ericsson-mpls&amp;revision=2015-06-30</capability>
    <capability>urn:ietf:params:xml:ns:yang:ospf-state?module=ospf-state&amp;revision=2015-06-09</capability>
    <capability>urn:ietf:params:xml:ns:yang:context-state?module=context-state&amp;revision=2015-06-05</capability>
    <capability>urn:ietf:params:xml:ns:yang:ericsson-context?module=ericsson-context&amp;revision=2015-07-08</capability>
    <capability>urn:ietf:params:xml:ns:yang:ericsson-config?module=ericsson-config&amp;revision=2015-06-25</capability>
    <capability>urn:ietf:params:xml:ns:yang:ericsson-types?module=ericsson-types&amp;revision=2015-06-16</capability>
    <capability>urn:cesnet:tmc:netopeer:1.0?module=netopeer-cfgnetopeer&amp;revision=2013-02-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-server?module=ietf-netconf-server&amp;revision=2014-01-24&amp;features=ssh,outbound-ssh</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2013-03-26</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2010-06-09</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2011-08-07</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-03-08&amp;features=writable-running,candidate,rollback-on-error,validate,startup</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2010-09-24</capability>
  </capabilities>
  <session-id>8</session-id>
</hello>
]]>]]><?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability>
   <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=scp,file</capability>
    <capability>http://netconfcentral.org/ns/toaster?module=toaster&amp;revision=2009-11-20</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2012-02-22</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2010-06-09</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2011-08-07</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-03-08&amp;features=writable-running,candidate,rollback-on-error,validate,startup,url</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2010-09-24</capability>
  </capabilities>
</hello>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="112"
     xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
     xmlns:eospf="urn:ietf:params:xml:ns:yang:ericsson-ospf"
     xmlns:econtext="urn:ietf:params:xml:ns:yang:ericsson-context"
     xmlns:econfig="urn:ietf:params:xml:ns:yang:ericsson-config">
  <edit-config>
    <target>
      <running />
    </target>
        <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <econfig:contexts>
   <econtext:context>
   <econtext:context-name>local</econtext:context-name>
   <econtext:router>
   <eospf:ospf>
        <eospf:ospf>1</eospf:ospf>
            <eospf:area>
          <eospf:area>0.0.0.0</eospf:area>
                    <eospf:interface>
                 <eospf:interface>eth1</eospf:interface>  
                 <eospf:flood-reduction/>                    
                    </eospf:interface>
        </eospf:area>
        </eospf:ospf>
        </econtext:router>
   </econtext:context>
   </econfig:contexts>
   </config>
  </edit-config>
</rpc>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:eospf="urn:ietf:params:xml:ns:yang:ericsson-ospf" xmlns:econtext="urn:ietf:params:xml:ns:yang:ericsson-context" xmlns:econfig="urn:ietf:params:xml:ns:yang:ericsson-config" message-id="112">
 <ok/>
</rpc-reply>
]]>]]>

**Comment by rkrejci** [comment]
You are right that in this case, libnetconf does not follow RFC strictly.

First, I expect, that you don't have validation files generated (RelaxNG and Schematron), otherwise you would get information that datastore fails to validate, but you are right that it is 'operation-failed' tag, not the 'unknown-element'. 

This validation process is actually mostly (it detects missing keys for example, but it is because it needs them, but in case of leafs, libnetconf does not need them to anything, so it does not check them) the only way how libnetconf gets know that something in the data is not correct.

And second, I expect that you don't have any transAPI module assigned to the ericsson-config data model. Because when there is a transAPI module, libnetconf builds a diff tree to get know what changed from the previous configuration data to call appropriate transAPi callbacks. In this case, I'm not sure which kind of rpc-error you will get, but you should get one, because libnetconf needs data model to build the diff tree and it won't be able to get any information about the created flood-reduction leaf (I wasn't able to test this now, but it should work this way).

libnetconf was developed with focus on NETCONF, YANG stuff was added later and it is not as well integrated as I'd wish. That's why I'm currently working on libyang, which should help to solve many of these issues in a future libnetconf version.
