### ISSUE TITLE
the fix the libnetconf issue 71 does not work. please help check

### ISSUE THREAD

**Issue by jinxud** [CESNET/libnetconf#72]
hi

this fix: BUGFIX ext_model consolidation according to features:https://github.com/CESNET/libnetconf/commit/7be8abf8bd887fa126faa3caa25d89d77a4a70bf

I verify the fix, but it does not work for augment model. in ncds_update_features(), 
if (!xmlStrcmp(node->name, BAD_CAST "augment")) -> it always false. seems it cannot find augment. but I printout the datastore->ext_model, there is augment, and ospf model is augment.

could you help confirm?

Thanks

**Comment by jinxud** [comment]
in ncds_update_features, it only search the top level of the ext_model. it would not include "augment". I guess the intention is to do recursion check in feature_check. but when the features is null, the feature_check will return and will not do the recursion check. I think that is the reason the fix does not work.

**Comment by rkrejci** [comment]
Issue #71 is reopened, keep the communication there.
