### ISSUE TITLE
which is the libxml2 minimal version for libnetconf 0.9.x?

### ISSUE THREAD

**Issue by nanzhao** [CESNET/libnetconf#73]
From the build dependency, I only know libnetconf need libxml2. But which is the libxml2 minimal version for libnetconf 0.9.x?

**Comment by rkrejci** [comment]
I'm currently using 2.9.1 and we are not aware (it doesn't mean there aren't some) of any compatibility issues in libxml2 API. Do you have any specific issues?

**Comment by nanzhao** [comment]
Our exsiting product uses the libxml2 2.6.9. So we are trying to combine libnetconf with libxml2 2.6.9. I will update the result later.
