### ISSUE TITLE
rpc error reply, no detailed information about which item validate failed

### ISSUE THREAD

**Issue by classcwnd** [CESNET/libnetconf#80]
Recently, We found if netconf message validation failed due to model check, libnetconf alway return following rpc error reply.
So we have to spend lots of time to find which command triggers the error. 
Could you improve libnetconf to print more detailed validation error information?
  
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:eospf="urn:ietf:params:xml:ns:yang:my-ospf" xmlns:econtext="urn:ietf:params:xml:ns:yang:my-context" xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" message-id="112">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Datastore fails to validate (Element data failed to validate content)</error-message>
  </rpc-error>
  <default:rpc-error xmlns:default="urn:ietf:params:xml:ns:netconf:base:1.0">
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>Datastore fails to validate (Extra element contexts in interleave)</error-message>
  </default:rpc-error>
</rpc-reply>
]]>]]>
```

**Comment by michalvasko** [comment]
Hi,
I am afraid it is not possible at the moment. We are using libxml2 RelaxNG validation whose error messages are really bad, as you can see. If you can't find out what is wrong with your configuration, the last resort is exporting the invalid configuration into a file and performing manual validation on it using yang2dsdl with the option "-j", jing has much clearer errors. We are currently working on libyang and once it's finished and used in the next libnetconf, the messages should be much better, the validation will be handled by libyang directly.

Regards,
Michal

**Comment by classcwnd** [comment]
Hi Michal,

Could  you please give us an example to use yang2dsdl to validation?
What's the format of the configuration file, and does yang2dsdl need model validators?

Thanks,
Yu

**Comment by michalvasko** [comment]
Hi Yu,

you install it like any Linux software, generally either a package or, if not available, you may have to install from the source. This question does not relate to libnetconf in any way, please stay on topic.

Regards,
Michal

**Comment by classcwnd** [comment]
Hi Michal,

Sorry, I really don't know how to use jing, I found it is a java package. And there is no document describes how to integrate jing with yang2dsdl. So I am much appreciate if you can give more information about jing. Thank you very much.

BR,
Yu

**Comment by michalvasko** [comment]
Hi Yu,

from the output you posted my guess would be that all you need to do is install that package, which will install jing somewhere into $PATH and yang2dsdl will find it on its own. I am sorry, too, but this is the last reply you will get regarding this topic, this is a place for libnetconf issues, no other.
