### ISSUE TITLE
Entries are missed in output of filter message

### ISSUE THREAD

**Issue by classcwnd** [CESNET/libnetconf#81]
I list the input message and output message in attached files: 

Input: input message, the first subtree to get leaf ospf-spf-runs of ospf-area-entry 0.0.0.57, the second subtree to get leaf ospf-area-bdr-rtr-count of ospf-area-entry 0.0.0.57.
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="102"
     xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
     xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config"
     xmlns:ctx="urn:ietf:params:xml:ns:yang:context-state"
     xmlns:ospf="urn:ietf:params:xml:ns:yang:ospf-state" >
  <get>
    <filter type="subtree">
      <econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config">
        <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
          <ctx:context-name>local</ctx:context-name>
          <ctx:router>
            <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
              <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
              <ospf:ospf-area-entry>
                <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
                <ospf:ospf-spf-runs/>
              </ospf:ospf-area-entry>
              <ospf:ospf-area-entry>
                <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
                <ospf:ospf-area-bdr-rtr-count/>
              </ospf:ospf-area-entry>
            </ospf:ospf>
          </ctx:router>
        </ctx:context>
      </econfig:contexts-state>
    </filter>
  </get>
</rpc>
]]>]]>
```
      
Our pre-processing output: intermediate output message returned from our code to libnetconf, the first subtree get leaf ospf-spf-runs of ospf-area-entry 0.0.0.57 successfully, the second subtree get leaf ospf-area-bdr-rtr-count of ospf-area-entry 0.0.0.57 successfully.
```
<econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config" xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" xmlns:ctx="urn:ietf:params:xml:ns:yang:context-state" xmlns:ospf="urn:ietf:params:xml:ns:yang:ospf-state">
  <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
    <ctx:context-name>local</ctx:context-name>
    <ctx:router>
      <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
        <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-spf-runs>3</ospf:ospf-spf-runs>
        </ospf:ospf-area-entry>
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-area-bdr-rtr-count>0</ospf:ospf-area-bdr-rtr-count>
        </ospf:ospf-area-entry>
      </ospf:ospf>
    </ctx:router>
  </ctx:context>
</econfig:contexts-state>
```
  
Actual output: output message filtered by libnetconf, leaf ospf-area-bdr-rtr-count of ospf-area-entry 0.0.0.57 is removed in ncxml_subtree_filter.
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" xmlns:ctx="urn:ietf:params:xml:ns:yang:context-state" xmlns:ospf="urn:ietf:params:xml:ns:yang:ospf-state" message-id="102">
  <data>
    <econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config" xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" xmlns:ctx="urn:ietf:params:xml:ns:yang:context-state" xmlns:ospf="urn:ietf:params:xml:ns:yang:ospf-state">
      <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
        <ctx:context-name>local</ctx:context-name>
        <ctx:router>
          <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
            <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
            <ospf:ospf-area-entry>
              <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
              <ospf:ospf-spf-runs>3</ospf:ospf-spf-runs>
            </ospf:ospf-area-entry>
            <ospf:ospf-area-entry>
              <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
            </ospf:ospf-area-entry>
          </ospf:ospf>
        </ctx:router>
      </ctx:context>
    </econfig:contexts-state>
  </data>
</rpc-reply>
]]>]]>
```

Expect output:
```
<econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config" xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" xmlns:ctx="urn:ietf:params:xml:ns:yang:context-state" xmlns:ospf="urn:ietf:params:xml:ns:yang:ospf-state">
  <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
    <ctx:context-name>local</ctx:context-name>
    <ctx:router>
      <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
        <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-spf-runs>3</ospf:ospf-spf-runs>
        </ospf:ospf-area-entry>
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-area-bdr-rtr-count>0</ospf:ospf-area-bdr-rtr-count>
        </ospf:ospf-area-entry>
      </ospf:ospf>
    </ctx:router>
  </ctx:context>
</econfig:contexts-state>
```

As per the algorithm of ncxml_subtree_filter, the code compares config_node (run-time data in this example) with filter_node, config_node is removed if it’s not consistent with filter_node. 
However, for each config_node, the code loops through all filter_node and compares with config_node, which may cause config_node is compared with non-corresponding filter_node . In this example: 
1.	Compare below config_node and filter_node, it’s correct. 
Config_node:
``` 
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-spf-runs>3</ospf:ospf-spf-runs>
        </ospf:ospf-area-entry>
```
Filter_node:
```
              <ospf:ospf-area-entry>
                <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
                <ospf:ospf-spf-runs/>
              </ospf:ospf-area-entry>
```
2.	Compare below config_node and filter_node, then leaf ospf-area-bdr-rtr-count is removed. 
Config_node:
```
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-area-bdr-rtr-count>0</ospf:ospf-area-bdr-rtr-count>
        </ospf:ospf-area-entry>
```
Filter_node:
``` 
              <ospf:ospf-area-entry>
                <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
                <ospf:ospf-spf-runs/>
              </ospf:ospf-area-entry>
```

**Comment by rkrejci** [comment]
I believe that your expectations are wrong. RFC 6241 says:
```
Specific  data instances are not duplicated in the response in the event that
the request contains multiple filter subtree expressions that select the same data.
```
It means that actually both is wrong - your expectations as well as the current output. You expect `ospf-area-entry` with id `0.0.0.57` to be duplicated in the result, but they shouldn't be duplicated (and they are, but in a different way than you expect).

To get the data you want, you can use the following filter:
```
      <econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config">
        <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
          <ctx:context-name>local</ctx:context-name>
          <ctx:router>
            <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
              <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
              <ospf:ospf-area-entry>
                <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
                <ospf:ospf-spf-runs/>
                <ospf:ospf-area-bdr-rtr-count/>
              </ospf:ospf-area-entry>
            </ospf:ospf>
          </ctx:router>
        </ctx:context>
      </econfig:contexts-state>
```
Expected output in this case is:
```
<econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config" xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" xmlns:ctx="urn:ietf:params:xml:ns:yang:context-state" xmlns:ospf="urn:ietf:params:xml:ns:yang:ospf-state">
  <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
    <ctx:context-name>local</ctx:context-name>
    <ctx:router>
      <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
        <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-spf-runs>3</ospf:ospf-spf-runs>
          <ospf:ospf-area-bdr-rtr-count>0</ospf:ospf-area-bdr-rtr-count>
        </ospf:ospf-area-entry>
      </ospf:ospf>
    </ctx:router>
  </ctx:context>
</econfig:contexts-state>
```
Is this _solution_ ok for you?

**Comment by classcwnd** [comment]
For example, if list has two keys: key_1 and key2, and two other leafs: leaf_3 and leaf_4. Assume there are 3 instances of list as below: 
| | key_1 | key_2 | leaf_3 | leaf_4
------------ | ------------ | ------------ | ------------ | ------------
instance_1 | A | X | O | P
instance_2 | A | Y | Q | R
instance_3 | B | Y | S | T
Use below filter to get run-data: 
<list>
  <key_1>A</key_1>
  <leaf_3/>
</list>
<list>
  <key_2>Y</key_2>
  <leaf_4/>
</list>


First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column


key_1 | key_2 | leaf_3 | leaf_4
------------ | ------------- | ------------- | -------------
instance_1 | A | A | A
instance_2 | B | A | A

For the first subtree filter, it can get leaf_3 of instance_1 and instance_2. For the second subtree filter, it can get leaf_4 of instance_2 and instance_3. Instance_2 is duplicated in the response, but instance_1 and instance_3 are not duplicated in the response. As user, I can’t forecast whether the first subtree filter and the second subtree filter will get the same instance or not. 
Is this scenario not allowed as per RFC6241?

**Comment by classcwnd** [comment]
In fact, following is our original issue, which is related to multiple-keys model. To simplify the issue, we use a single-key model to describe it at the beginning.
For example, if list has two keys: key_1 and key2, and two other leafs: leaf_3 and leaf_4. Assume there are 3 instances of list as below:
 
 | key_1 | key_2 | leaf_3 | leaf_4
------------ | ------------- | ------------- | ------------- | -------------
instance_1 | A | X | O | P
instance_2 | A | Y | Q | R
instance_3 | B | Y | S | T

Use below filter to get run-data:
``` 
<list>
  <key_1>A</key_1>
  <leaf_3/>
</list>
<list>
  <key_2>Y</key_2>
  <leaf_4/>
</list>
````
For the first subtree filter, it can get leaf_3 of instance_1 and instance_2. 
For the second subtree filter, it can get leaf_4 of instance_2 and instance_3. 
Instance_2 is duplicated in the response, but instance_1 and instance_3 are not duplicated in the response. 
As user, I can’t forecast whether the first subtree filter and the second subtree filter will get the same instance or not. 
Is this scenario not allowed as per RFC6241 or otherwise current libnetconf can not support it?

**Comment by rkrejci** [comment]
ok, this scenario make sense. Anyway, it should follow what I cited from RFC 6241. So, from my perspective, the result should include all 3 instances only once. `instance_1` will include only `leaf_3`, `instance_2` will include both `leaf_3` and `leaf_4` and `instance_3` will include only `leaf_4`:
```
<list>
  <key_1>A</key_1>
  <key_2>X</key_2>
  <leaf_3>O</leaf_3>
</list>
<list>
  <key_1>A</key_1>
  <key_2>Y</key_2>
  <leaf_3>Q</leaf_3>
  <leaf_4>R</leaf_4>
</list>
<list>
  <key_1>B</key_1>
  <key_2>Y</key_2>
  <leaf_4>T</leaf_4>
</list>
```

It is not currently supported in libnetconf this way, but before going to fix it, I want to agree our understanding of the correct result. So, do you thing that this result is ok?

**Comment by classcwnd** [comment]
Yes, we think your results are correct. 
We also have a question to be confirmed. 
Our pre-preocessing output, which shall be the input of libnetconf ncxml_merge() and ncxml_filter(), may have duplicated instance.
Can your fix handle this input and get the correct results we both agree?  

Our pre-processing output: intermediate output message returned from our code to libnetconf, both the first and second subtrees are ospf-area-entry 0.0.0.57.
```
<econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config" xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" xmlns:ctx="urn:ietf:params:xml:ns:yang:context-state" xmlns:ospf="urn:ietf:params:xml:ns:yang:ospf-state">
  <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
    <ctx:context-name>local</ctx:context-name>
    <ctx:router>
      <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
        <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-spf-runs>3</ospf:ospf-spf-runs>
        </ospf:ospf-area-entry>
        <ospf:ospf-area-entry>
          <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
          <ospf:ospf-area-bdr-rtr-count>0</ospf:ospf-area-bdr-rtr-count>
        </ospf:ospf-area-entry>
      </ospf:ospf>
    </ctx:router>
  </ctx:context>
</econfig:contexts-state>
```

**Comment by rkrejci** [comment]
I already thought about it, the problem is that (from the first sight) it requires preprocessing the filter, so some additional resources (at least time). Honestly, I'm not excited from this, but it seems that it doesn't break anything in RFC 6241 :( I'll try to integrate it somehow directly into the filter processing minimizing performance impact, but I cannot promise that it will be possible.

Anyway, I'm currently busy with some other work and preparing for IETF93 next week, so fixing this may get some time.

**Comment by classcwnd** [comment]
Yes, RFC 6241 only says the duplicated instances can not appear in response, i.e. data of duplicated instance can be in sub multiple trees of request. So our request message does not break the rule of RFC (even the single key request example at the beginning), am I right? 

Thanks for your time to handle this hard issue. It is ok for me. :)

**Comment by rkrejci** [comment]
Yes, I thing you are right. But the solving this issue definitely won't be easy, I'm afraid that it can lead to changing current filtering approach significantly :(

**Comment by classcwnd** [comment]
Yes, I also think so. I would thankful for your great effort.

**Comment by rkrejci** [comment]
I spent some time on solving this issue. Filter was improved but it still does not work as we proposed here. There are too many corner cases for selecting list instances using multiple selection nodes in filter to automatically handle them all in the current code.

We plan to completely rewrite filter code due to moving from libxml2 to libyang this autumn. Therefore, I'm not willing to spend much time on this right now. 

Anyway, here is a hint how to get the desired result using appropriate filters. So, to get the result I described above in my example, you have to combine the list selection manually (not, that it must be first):
```
<list>
  <key_1>A</key_1>
  <key_2>Y</key_2>
  <leaf_3/>
  <leaf_4/>
</list>
<list>
  <key_1>A</key_1>
  <leaf_3/>
</list>
<list>
  <key_2>Y</key_2>
  <leaf_4/>
</list>
```
and for your case, you will have to use the filter as follows:
```
<econfig:contexts-state xmlns="urn:ietf:params:xml:ns:yang:my-config">
  <ctx:context xmlns="urn:ietf:params:xml:ns:yang:context-state">
    <ctx:context-name>local</ctx:context-name>
      <ctx:router>
        <ospf:ospf xmlns="urn:ietf:params:xml:ns:yang:ospf-state">
          <ospf:ospf-state-instance-id>201</ospf:ospf-state-instance-id>
          <ospf:ospf-area-entry>
            <ospf:ospf-area-id>0.0.0.57</ospf:ospf-area-id>
            <ospf:ospf-spf-runs/>
            <ospf:ospf-area-bdr-rtr-count/>
          </ospf:ospf-area-entry>
        </ospf:ospf>
      </ctx:router>
    </ctx:context>
  </econfig:contexts-state>
```
It seems to me that it is easier to format filter request than make libnetconf (using C and libxml2) to do it automatically. If you have other opinion, I'm quite open to accept your patches.
