### ISSUE TITLE
Implement ability to disable ssh auth types

### ISSUE THREAD

**Issue by xboxyp** [CESNET/libnetconf#88]
Right now, sshauth_pref is a static and initialized to all three types. So, if one auth method fails, it fallbacks to other. But I think, it is good to have support for letting users to disable a method so that the application can try with only one type. Only way to achieve that right now i think is to provide dummy callback apis for sshauth_password, for example!

**Comment by rkrejci** [comment]
See the `preference` parameter description of the [nc_ssh_pref()](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/db/d52/group__session.html#ga13119fdaa84544bf254bdb35ffdf83e0) function: **_Negative value disables the given authentication type._**
