### ISSUE TITLE
RFC6022 compliant issues

### ISSUE THREAD

**Issue by luowei-eric** [CESNET/libnetconf#89]
Hi,

We did RFC6022 compliance test on Libnetconf. Three non-compliance were found. Could you please check it? Thanks.
1. Can not retrieve /capabilites info. It seems it is not implemented.
2. For the <get-schema> operation, according to section5(page 24), If the parameter 'version' is not present, and more than one version of the schema exists on the server, a 'data-not-unique' error should be returned. But Libnetconf reply OK.
3. The Libnetconf doesn't validate the namespace in hello message. According to section3.1(page13) in RFC6241, the namespace should be "urn:ietf:params:xml:ns:netconf:base:1.0". I think this is a RFC6241 non-compliance issue.

Regards,
Wei

**Comment by rkrejci** [comment]
ad point 2 - I tried it and it seems that it works fine.

In my server, I had 2 revisions of the test module (this is content of the <get> result):

```
      <schema>
        <identifier>test</identifier>
        <version>2015-08-06</version>
        <format>yin</format>
        <namespace>http://www.example.com/test</namespace>
        <location>NETCONF</location>
      </schema>
      <schema>
        <identifier>test</identifier>
        <version>2015-08-06</version>
        <format>yang</format>
        <namespace>http://www.example.com/test</namespace>
        <location>NETCONF</location>
      </schema>
      <schema>
        <identifier>test</identifier>
        <version>2015-06-29</version>
        <format>yin</format>
        <namespace>http://www.example.com/test</namespace>
        <location>NETCONF</location>
      </schema>
      <schema>
        <identifier>test</identifier>
        <version>2015-06-29</version>
        <format>yang</format>
        <namespace>http://www.example.com/test</namespace>
        <location>NETCONF</location>
      </schema>
```

I sent the following request (missing version parameter):
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  <get-schema xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
    <identifier>test</identifier>
    <format>yin</format>
  </get-schema>
</rpc>
```

and received the error reply:
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>data-not-unique</error-app-tag>
    <error-message>Some unspecified error occurred.</error-message>
  </rpc-error>
</rpc-reply>
```

I don't like the message (so i changed it), but error was returned. Can you more describe your case?
