### ISSUE TITLE
In function 'nc_session_connect_tls_socket':  error: 'struct nc_session' has no member named 'libssh2_socket'

### ISSUE THREAD

**Issue by gupendrak** [CESNET/libnetconf#95]
MyMachine:/var/SW/libnetconf # ./configure --enable-tls
....
this has passed with no errors.
....
Bur tried to run make, I'm getting this error.
MyMachine:/var/SW/libnetconf # make
./libtool --tag=CC --quiet --mode=compile gcc -Wall -I/usr/include/libxml2 -I/usr/include/libxml2  -O3 -DNDEBUG -fvisibility=hidden  -DNC_WORKINGDIR_PATH=\"//var/lib/libnetconf/\" -DSETBIT=0  -DRCSID=\""built from git 0388dfaf59732796be26"\" -DENABLE_TLS -DPOSIX_SHM -I/var/SW/libnetconf/src  -fPIC -c src/tls.c -o .obj/src/tls.lo
src/tls.c: In function 'nc_tls_init':
src/tls.c:107: warning: implicit declaration of function 'TLSv1_2_client_method'
src/tls.c:107: warning: passing argument 1 of 'SSL_CTX_new' makes pointer from integer without a cast
src/tls.c: In function 'nc_session_connect_tls_socket':
src/tls.c:215: error: 'struct nc_session' has no member named 'libssh2_socket'
src/tls.c:236: warning: implicit declaration of function 'pthread_mutexattr_settype'
src/tls.c:236: error: 'PTHREAD_MUTEX_RECURSIVE' undeclared (first use in this function)
src/tls.c:236: error: (Each undeclared identifier is reported only once
src/tls.c:236: error: for each function it appears in.)
make: *** [.obj/src/tls.lo] Error 1
MyMachine:/var/SW/libnetconf #

FYI. I'm trying to use netopeer and I must use 'tls' as transport protocol.

Any help/suggestion in this regard would be appreciated.

**Comment by michalvasko** [comment]
Hi,

to begin with, those tls.c lines do not match the lines in the current master branch although RCSID git revision is the last commit, so I must assume you made some changes to the file yourself and with that I can't give you any other advice than to checkout the master branch unless you can explain those differences another way.

Regards,
Michal
