### ISSUE TITLE
ssh options

### ISSUE THREAD

**Issue by xboxyp** [CESNET/libnetconf#99]
need an api to set callback to set ssh options of an ssh session

**Comment by michalvasko** [comment]
Hi,

I assume you're talking about the client API, since to use the server API you need to have an SSH channel created. So, what options in particular would you like to change?

Regards,
Michal

**Comment by xboxyp** [comment]
Thanks for the response Michal. Yes, I meant client api. 

I am looking for SSH_OPTIONS_STRICTHOSTKEYCHECK. 

But i think it adds value to have an api to set any chosen ssh options. For now, my workaround is to set my own callback for hostkey checking as it has a callback. But i think there is no callback for each ssh option, so my workaround is not possible for other ssh options.

Thanks,
Prashanth

**Comment by michalvasko** [comment]
Hi Prashanth,

please verify that when you use the new function nc_sessioon_connect_libssh_sess() it works as you would expect, thank you.

Regards,
Michal
